Repository tyler-technologies-oss/forge, pull requests merged in 2022-10, with the labels that each got.

#149 feat: showHourOptions for time-picker
  src/demo/scripts/time-picker.js
  src/lib/time-picker/time-picker-constants.ts
  src/lib/time-picker/time-picker-foundation.ts
  src/lib/time-picker/time-picker.ts
  src/stories/src/components/time-picker/time-picker-args.ts
  src/stories/src/components/time-picker/time-picker.mdx
  src/stories/src/components/time-picker/time-picker.stories.tsx
  src/test/spec/time-picker/time-picker.spec.ts
Labels: skip-release

#151 fix(inline-message): set host to be a block level element
  src/lib/inline-message/inline-message.scss
Labels: skip-release

#152 fix(table): add checkbox to component dependencies
  src/lib/table/table.ts
Labels: skip-release

#155 fix(file-picker): fix helper text slotted styles and dimensions
  src/lib/file-picker/_mixins.scss
Labels: skip-release

#150 fix(drawer): fixes drawer initialization state when defaulting to closed
  src/lib/drawer/base/base-drawer-foundation.ts
  src/lib/drawer/modal-drawer/modal-drawer-foundation.ts
  src/test/spec/drawer/modal-drawer.spec.ts
Labels: bug, patch

#156 chore: post release notes to slack
  auto.config.ts
  package-lock.json
  package.json
Labels: skip-release

#157 chore: support node 16
  .github/workflows/auto-pr-check.yml
  .github/workflows/build-pr.yml
  .github/workflows/build-release.yml
  .github/workflows/cleanup-pr.yml
  .npmrc
  package-lock.json
  package.json
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/stories/.npmrc
  src/stories/package-lock.json
  src/stories/package.json
Labels: skip-release

#164 fix(select): fix to ensure `--forge-select-font-size` CSS custom prop…
  src/lib/chip-field/_selector.scss
  src/lib/field/_base.scss
  src/lib/field/_selector.scss
  src/lib/select/select/_selector.scss
Labels: skip-release

#163 fix(autocomplete): fixed a bug where opening the dropdown via down arrow key would not activate the selected option
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-foundation.ts
  src/test/spec/autocomplete/autocomplete.spec.ts
  src/tsconfig-test.json
Labels: skip-release

#168 fix: fixed duplicate asterisk characters on required form field labels in Safari
  src/lib/chip-field/chip-field-adapter.ts
  src/lib/field/field-adapter.ts
  src/lib/field/field-foundation.ts
  src/lib/quantity-field/_mixins.scss
  src/lib/quantity-field/quantity-field-adapter.ts
  src/lib/quantity-field/quantity-field-foundation.ts
  src/lib/text-field/text-field-adapter.ts
Labels: skip-release

#167 feat(app-bar-profile-button): allow for customizing the text on the sign out and profile buttons
  src/demo/index.html
  src/lib/app-bar/profile-button/app-bar-profile-button-adapter.ts
  src/lib/app-bar/profile-button/app-bar-profile-button-constants.ts
  src/lib/app-bar/profile-button/app-bar-profile-button-foundation.ts
  src/lib/app-bar/profile-button/app-bar-profile-button.ts
  src/lib/profile-card/profile-card-adapter.ts
  src/lib/profile-card/profile-card-constants.ts
  src/lib/profile-card/profile-card-foundation.ts
  src/lib/profile-card/profile-card.html
  src/lib/profile-card/profile-card.ts
  src/stories/src/components/app-bar-profile/app-bar-profile.mdx
  src/test/spec/app-bar/profile-button/app-bar-profile-button.spec.ts
Labels: skip-release

#166 fix(chip): change default `height` style to use `auto` to accommodate content height
  src/lib/chip-field/_base.scss
  src/lib/chip-field/_variables.scss
  src/lib/chips/chip/_mixins.scss
  src/lib/chips/chip/_variables.scss
  src/stories/src/components/chips/chips.mdx
Labels: skip-release

#169 fix(table): ignore filter row checkboxes when toggling select column state
  src/lib/table/table-utils.ts
  src/stories/src/components/table/table.mdx
Labels: skip-release

#171 chore: optimize pr-check workflow to limit dependency installation to
  .github/workflows/auto-pr-check.yml
Labels: skip-release

#174 docs(keyboard-shortcut): add storybook docs for keyboard shortcuts
  package-lock.json
  src/lib/keyboard-shortcut/keyboard-shortcut-foundation.ts
  src/lib/keyboard-shortcut/keyboard-shortcut-utils.ts
  src/lib/keyboard-shortcut/keyboard-shortcut.ts
  src/stories/package-lock.json
  src/stories/package.json
  src/stories/src/components/keyboard-shortcut/code/keyboard-shortcut-basic.ts
  src/stories/src/components/keyboard-shortcut/keyboard-shortcut-arg.ts
  src/stories/src/components/keyboard-shortcut/keyboard-shortcut.mdx
  src/stories/src/components/keyboard-shortcut/keyboard-shortcut.stories.tsx
Labels: skip-release

#160 feat: expand nullable types to allow undefined
  .eslintrc.json
  src/lib/app-bar/app-bar.ts
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/autocomplete/autocomplete.ts
  src/lib/bottom-sheet/bottom-sheet-adapter.ts
  src/lib/calendar/calendar-foundation.ts
  src/lib/calendar/calendar-utils.ts
  src/lib/calendar/calendar.ts
  src/lib/calendar/core/calendar-base.ts
  src/lib/chips/chip/chip-foundation.ts
  src/lib/chips/chip/chip.ts
  src/lib/color-picker/color-picker-foundation.ts
  src/lib/color-picker/color-picker.ts
  src/lib/core/utils/date-utils.ts
  src/lib/date-picker/base/base-date-picker-adapter.ts
  src/lib/date-picker/base/base-date-picker-constants.ts
  src/lib/date-picker/base/base-date-picker-foundation.ts
  src/lib/date-picker/base/base-date-picker.ts
  src/lib/date-picker/date-picker-foundation.ts
  src/lib/date-picker/date-picker.ts
  src/lib/date-range-picker/date-range-picker-foundation.ts
  src/lib/date-range-picker/date-range-picker.ts
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-foundation.ts
  src/lib/dialog/dialog.ts
  src/lib/file-picker/file-picker-adapter.ts
  src/lib/file-picker/file-picker-foundation.ts
  src/lib/file-picker/file-picker.ts
  src/lib/floating-label/floating-label-adapter.ts
  src/lib/keyboard-shortcut/keyboard-shortcut-foundation.ts
  src/lib/keyboard-shortcut/keyboard-shortcut-utils.ts
  src/lib/keyboard-shortcut/keyboard-shortcut.ts
  src/lib/menu/menu.ts
  src/lib/popup/popup.ts
  src/lib/quantity-field/quantity-field-adapter.ts
  src/lib/table/table-utils.ts
  src/lib/table/table.ts
  src/lib/time-picker/time-picker-foundation.ts
  src/lib/time-picker/time-picker-utils.ts
  src/lib/time-picker/time-picker.ts
  src/lib/tooltip/tooltip.ts
  src/lib/view-switcher/view-switcher.ts
  src/test/spec/date-range-picker/date-range-component-delegate.spec.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
Labels: minor

#173 chore(build): update Forge CLI to enable ESM minification
  package-lock.json
  package.json
Labels: skip-release

#172 fix(paginator): fixed change event state reconciliation
  src/lib/paginator/paginator-foundation.ts
  src/test/spec/paginator/paginator.spec.ts
Labels: skip-release

#176 fix(table): fixed default select height in column filter
  src/lib/table/_mixins.scss
Labels: bug, patch
