Repository tyler-technologies-oss/forge, pull requests merged in 2022-11, with the labels that each got.

#182 chore: update Angular framework usage
  src/stories/src/guides/framework-usage.stories.mdx
Labels: skip-release

#185 feat(badge): added leading and trailing slots with support for icons
  src/lib/badge/_mixins.scss
  src/lib/badge/badge.html
  src/stories/src/components/badge/badge-arg-types.ts
  src/stories/src/components/badge/badge.mdx
  src/stories/src/components/badge/badge.stories.tsx
Labels: enhancement, skip-release

#187 docs(app-bar): fixed app-bar-profile-button references to use correct element name
  src/demo/index.html
  src/stories/src/components/app-bar-profile/app-bar-profile.mdx
  src/stories/src/components/app-bar/code/app-bar-full.ts
Labels: documentation, skip-release

#189 docs(button-toggle): corrects spelling error
  src/stories/src/components/button-toggle/button-toggle.mdx
Labels: skip-release

#192 docs(legal): use forge logo and add license info
  src/stories/StorybookMdxProvider.tsx
  src/stories/forge-theme.ts
  src/stories/preview-head.html
  src/stories/src/assets/forge-logo-full-color.svg
  src/stories/src/assets/forge-logo-full-white.svg
  src/stories/src/core/library-version.tsx
  src/stories/src/forge.stories.mdx
Labels: skip-release

#193 chore: update templates and fix license text in sb
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_component.md
  src/stories/src/forge.stories.mdx
Labels: skip-release
