Repository tyler-technologies-oss/forge, pull requests merged in 2023-11, with the labels that each got.

#421 chore: general cleanup and consistency sweep
  .stylelintrc
  src/dev/pages/circular-progress/circular-progress.html
  src/dev/pages/circular-progress/circular-progress.ts
  src/dev/pages/linear-progress/linear-progress.html
  src/dev/pages/linear-progress/linear-progress.ts
  src/lib/button/button-constants.ts
  src/lib/checkbox/checkbox.scss
  src/lib/circular-progress/_core.scss
  src/lib/circular-progress/circular-progress-constants.ts
  src/lib/circular-progress/circular-progress-foundation.ts
  src/lib/circular-progress/circular-progress.scss
  src/lib/circular-progress/circular-progress.test.ts
  src/lib/circular-progress/circular-progress.ts
  src/lib/constants.ts
  src/lib/core/base/base-adapter.ts
  src/lib/core/styles/_utils.scss
  src/lib/core/styles/tokens/button/_tokens.scss
  src/lib/core/styles/tokens/circular-progress/_tokens.scss
  src/lib/core/styles/tokens/focus-indicator/_tokens.scss
  src/lib/core/styles/tokens/linear-progress/_tokens.scss
  src/lib/linear-progress/_core.scss
  src/lib/linear-progress/linear-progress-constants.ts
  src/lib/linear-progress/linear-progress-foundation.ts
  src/lib/linear-progress/linear-progress.scss
  src/lib/linear-progress/linear-progress.test.ts
  src/lib/linear-progress/linear-progress.ts
  src/lib/slider/slider.scss
  src/lib/switch/switch.scss
Labels: skip-release, @next

#423 chore(list-item): improve anchor handling and semantics
  src/dev/pages/list/list.ejs
  src/lib/list/list-item/list-item-adapter.ts
  src/lib/list/list-item/list-item-constants.ts
  src/lib/list/list-item/list-item-foundation.ts
  src/lib/list/list-item/list-item.html
  src/lib/list/list-item/list-item.ts
  src/lib/list/list.test.ts
Labels: skip-release, @next

#427 [@next] chore: refactor slider to extend `BaseFormComponent`
  src/dev/pages/slider/slider.ejs
  src/lib/checkbox/checkbox-adapter.ts
  src/lib/checkbox/checkbox.ts
  src/lib/core/base/base-component.ts
  src/lib/slider/slider-adapter.ts
  src/lib/slider/slider.test.ts
  src/lib/slider/slider.ts
  src/lib/switch/switch-adapter.ts
  src/lib/switch/switch.test.ts
  src/lib/switch/switch.ts
Labels: skip-release, @next

#432 feat(floating-action-button): refactor FAB to use base button and tokens
  src/dev/pages/app-bar/app-bar.ejs
  src/dev/pages/app-bar/app-bar.ts
  src/dev/pages/fab/fab.ejs
  src/dev/pages/fab/fab.html
  src/dev/pages/fab/fab.scss
  src/dev/pages/fab/fab.ts
  src/dev/pages/icon-button/icon-button.html
  src/dev/pages/icon-button/icon-button.ts
  src/lib/button/base/base-button.ts
  src/lib/button/button.test.ts
  src/lib/button/button.ts
  src/lib/constants.ts
  src/lib/core/styles/tokens/floating-action-button/_tokens.scss
  src/lib/core/styles/tokens/icon-button/_tokens.scss
  src/lib/core/styles/tokens/shape/_tokens.scss
  src/lib/core/styles/tokens/spacing/_tokens.scss
  src/lib/floating-action-button/_configuration.scss
  src/lib/floating-action-button/_core.scss
  src/lib/floating-action-button/_extended-fab-theme.scss
  src/lib/floating-action-button/_fab-custom-properties.scss
  src/lib/floating-action-button/_fab-theme.scss
  src/lib/floating-action-button/_fab.mixins.scss
  src/lib/floating-action-button/_token-utils.scss
  src/lib/floating-action-button/build.json
  src/lib/floating-action-button/floating-action-button-adapter.ts
  src/lib/floating-action-button/floating-action-button-component-delegate.ts
  src/lib/floating-action-button/floating-action-button-constants.ts
  src/lib/floating-action-button/floating-action-button-foundation.ts
  src/lib/floating-action-button/floating-action-button.html
  src/lib/floating-action-button/floating-action-button.scss
  src/lib/floating-action-button/floating-action-button.test.ts
  src/lib/floating-action-button/floating-action-button.ts
  src/lib/floating-action-button/forge-floating-action-button.scss
  src/lib/floating-action-button/index.scss
  src/lib/floating-action-button/index.ts
  src/lib/forge.scss
  src/lib/icon-button/icon-button-constants.ts
  src/lib/icon-button/icon-button.test.ts
  src/lib/icon-button/icon-button.ts
  src/lib/icon-button/index.ts
  src/lib/index.ts
  src/stories/src/components/fab/code/fab-default.ts
  src/stories/src/components/fab/code/fab-extended.ts
  src/stories/src/components/fab/code/fab-mini.ts
  src/stories/src/guides/getting-started.stories.mdx
  src/test/spec/floating-action-button/floating-action-button.spec.ts
Labels: minor, @next

#429 docs(button-area): add header slot to expansion panel example
  src/stories/src/components/button-area/code/button-area-default.ts
Labels: documentation, skip-release

#436 feat(paginator): added new `rangeLabelCallback` property to allow for controlling range label text externally
  src/dev/pages/paginator/paginator.html
  src/dev/pages/paginator/paginator.ts
  src/lib/paginator/paginator-constants.ts
  src/lib/paginator/paginator-foundation.ts
  src/lib/paginator/paginator.ts
  src/stories/src/components/paginator/paginator.mdx
  src/test/spec/paginator/paginator.spec.ts
Labels: minor

#438 feat(app-bar-search): refactored to use tokens and updated patterns and API
  src/dev/pages/app-bar/app-bar.ejs
  src/dev/src/partials/head.ejs
  src/lib/app-bar/app-bar/_core.scss
  src/lib/app-bar/app-bar/app-bar.scss
  src/lib/app-bar/search/_configuration.scss
  src/lib/app-bar/search/_core.scss
  src/lib/app-bar/search/_mixins.scss
  src/lib/app-bar/search/_token-utils.scss
  src/lib/app-bar/search/_variables.scss
  src/lib/app-bar/search/app-bar-search-adapter.ts
  src/lib/app-bar/search/app-bar-search-constants.ts
  src/lib/app-bar/search/app-bar-search-foundation.ts
  src/lib/app-bar/search/app-bar-search.html
  src/lib/app-bar/search/app-bar-search.scss
  src/lib/app-bar/search/app-bar-search.test.ts
  src/lib/app-bar/search/app-bar-search.ts
  src/lib/app-bar/search/index.scss
  src/lib/core/base/base-adapter.ts
  src/lib/core/styles/tokens/app-bar/search/_tokens.scss
  src/test/spec/app-bar/search/app-bar-search.fixture.html
  src/test/spec/app-bar/search/app-bar-search.spec.ts
Labels: minor, @next

#439 feat(button): add full width property/attribute
  src/dev/pages/button/button.ejs
  src/dev/pages/button/button.html
  src/dev/pages/button/button.scss
  src/dev/pages/button/button.ts
  src/lib/button/base/base-button-adapter.ts
  src/lib/button/base/base-button-foundation.ts
  src/lib/button/base/base-button.test.ts
  src/lib/button/base/base-button.ts
  src/lib/button/button-constants.ts
  src/lib/button/button-foundation.ts
  src/lib/button/button.scss
  src/lib/button/button.test.ts
  src/lib/button/button.ts
  src/lib/core/base/base-focusable-component.ts
Labels: minor, @next
