Repository tyler-technologies-oss/forge, pull requests merged in 2023-05, with the labels that each got.

#285 perf: checkbox, radio, and switch will now instantiate ripple upon first user interaction
  src/lib/button/button.ts
  src/lib/checkbox/checkbox-adapter.ts
  src/lib/checkbox/checkbox-foundation.ts
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-foundation.ts
  src/lib/icon-button/icon-button.ts
  src/lib/list/list-item/list-item-foundation.ts
  src/lib/radio/radio-adapter.ts
  src/lib/radio/radio-foundation.ts
  src/lib/ripple/forge-ripple.ts
  src/lib/switch/switch.ts
Labels: skip-release

#282 fix(linear-progress): updated the default `buffer` state to be `1` instead of `0`
  src/dev/pages/linear-progress/linear-progress.ts
  src/lib/linear-progress/linear-progress.ts
  src/stories/src/components/linear-progress/code/linear-progress-determinate.ts
  src/stories/src/components/linear-progress/linear-progress.mdx
  src/test/spec/linear-progress/linear-progress.spec.ts
Labels: skip-release

#276 feat: allow for using `<a>` element in place of `<button>` in `<forge-button>`, `<forge-icon-button>` and `<forge-fab>` components
  src/dev/pages/button/button.ejs
  src/dev/pages/button/button.scss
  src/dev/pages/button/button.ts
  src/dev/pages/fab/fab.ejs
  src/dev/pages/fab/fab.ts
  src/dev/pages/icon-button/icon-button.ejs
  src/dev/pages/icon-button/icon-button.ts
  src/lib/button/button-constants.ts
  src/lib/button/button.ts
  src/lib/floating-action-button/floating-action-button-constants.ts
  src/lib/icon-button/icon-button-constants.ts
  src/stories/src/components/button/button.mdx
  src/stories/src/components/fab/fab.mdx
  src/stories/src/components/icon-button/icon-button.mdx
Labels: skip-release

#288 fix(table): fixed a bug where the `pointer` cursor could be lost when `allowRowClick` is enabled
  src/lib/table/table-utils.ts
  src/test/spec/table/table.spec.ts
Labels: skip-release

#263 fix(color-picker): fixed initialization exceptions when properties were set before connected to DOM
  src/lib/color-picker/color-picker-foundation.ts
Labels: skip-release

#269 fix(autocomplete): keep dropdown open when selecting items in stateless + multiple mode
  src/lib/autocomplete/autocomplete-foundation.ts
  src/test/spec/autocomplete/autocomplete.spec.ts
Labels: skip-release

#274 fix(select): fixed a bug where the option group `builder` property was not being called
  src/dev/index.ejs
  src/dev/src/index.ts
  src/lib/core/utils/utils.ts
  src/lib/select/core/base-select-adapter.ts
  src/lib/select/core/select-utils.ts
  src/lib/select/option-group/option-group.ts
  src/test/spec/select/select.spec.ts
  src/tsconfig-test.json
Labels: skip-release

#278 feat(table): provided the column index to the `TableTemplateBuilder`
  src/dev/pages/table/table.ts
  src/lib/table/table-utils.ts
  src/lib/table/types.ts
  src/stories/src/components/table/table.mdx
Labels: skip-release

#279 feat(table): added new method `isColumnHidden()`
  src/lib/table/table-foundation.ts
  src/lib/table/table.ts
  src/stories/src/components/table/table.mdx
  src/test/spec/table/table.spec.ts
Labels: skip-release

#281 fix(file-picker): allow for setting disabled state before child `<button>` is in DOM
  src/lib/file-picker/file-picker-adapter.ts
  src/lib/file-picker/file-picker-foundation.ts
  src/lib/file-picker/file-picker.ts
Labels: skip-release

#283 feat(toolbar): various toolbar improvements
  src/dev/pages/toolbar/toolbar.html
  src/dev/pages/toolbar/toolbar.scss
  src/dev/pages/toolbar/toolbar.ts
  src/lib/toolbar/_mixins.scss
  src/lib/toolbar/toolbar.html
  src/lib/toolbar/toolbar.scss
  src/stories/src/components/toolbar/toolbar.mdx
Labels: skip-release

#284 fix(list-item): remove unused `::before` pseudo element from slotted elements
  src/lib/list/list-item/_mixins.scss
Labels: skip-release

#286 feat: added CSS custom property for controlling the internal `border-style` on select, text-field, and chip-field
  src/lib/field/_base.scss
  src/lib/field/_selector.scss
  src/stories/src/components/chip-field/chip-field.mdx
  src/stories/src/components/select/select.mdx
  src/stories/src/components/text-field/text-field.mdx
Labels: minor

#289 fix(chip-field): fixed a bug where clicking on the field would not propagate the click event
  src/dev/pages/chip-field/chip-field.ejs
  src/dev/pages/chip-field/chip-field.ts
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/chip-field/chip-field-adapter.ts
  src/lib/chip-field/chip-field-foundation.ts
Labels: skip-release

#293 fix(menu): fixed toggle element initialization
  src/lib/menu/menu-constants.ts
  src/lib/menu/menu-foundation.ts
  src/lib/menu/menu.ts
  src/test/spec/menu/menu.spec.ts
Labels: patch, skip-release

#290 fix(chip-field): fixed a bug where addon-end slot was not expanding full height as the field grew
  src/dev/pages/chip-field/chip-field.ejs
  src/lib/chip-field/_selector.scss
  src/lib/chip-field/chip-field.scss
Labels: patch, skip-release

#297 fix(quantity-field): remove increment and decrement buttons from the tab order by default
  src/dev/pages/quantity-field/quantity-field.ejs
  src/dev/pages/quantity-field/quantity-field.html
  src/dev/pages/quantity-field/quantity-field.ts
  src/dev/src/components.json
  src/lib/quantity-field/quantity-field-adapter.ts
  src/lib/quantity-field/quantity-field-foundation.ts
  src/lib/quantity-field/quantity-field.ts
  src/stories/src/components/quantity-field/quantity-field.mdx
Labels: patch, skip-release

#302 fix: stop propagation on `Escape` key events
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/calendar/calendar-foundation.ts
  src/lib/date-picker/base/base-date-picker-foundation.ts
  src/lib/menu/menu-foundation.ts
  src/lib/select/core/base-select-foundation.ts
  src/lib/time-picker/time-picker-foundation.ts
Labels: patch, skip-release

#294 feat(autocomplete): added new `filterText` property/attribute to allow for setting the filter text state manually (only applies when `allowUnmatched` is enabled)
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-constants.ts
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/autocomplete/autocomplete.ts
  src/stories/src/components/autocomplete/autocomplete.mdx
Labels: minor, skip-release

#295 feat(view-switcher): added new `--forge-view-switcher-width` CSS custom property
  src/lib/view-switcher/_mixins.scss
  src/stories/src/components/view-switcher/view-switcher.mdx
Labels: minor, skip-release

#308 fix(dialog): fixed a bug where moving the dialog within a scroll container would calculate an incorrect position
  src/lib/dialog/dialog-foundation.ts
  src/test/spec/dialog/dialog.spec.ts
Labels: patch, skip-release, storybook-preview

#301 fix(chip): fixed accessibility issues
  src/dev/pages/chips/chips.ejs
  src/dev/pages/chips/chips.ts
  src/lib/chips/chip-set/chip-set-adapter.ts
  src/lib/chips/chip-set/chip-set-foundation.ts
  src/lib/chips/chip-set/chip-set.ts
  src/lib/chips/chip/_mixins.scss
  src/lib/chips/chip/chip-adapter.ts
  src/lib/chips/chip/chip-constants.ts
  src/lib/chips/chip/chip-foundation.ts
  src/lib/chips/chip/chip.html
  src/lib/chips/chip/chip.ts
  src/lib/ripple/forge-ripple.ts
  src/stories/src/components/chips/chips.mdx
  src/test/spec/chips/chips.spec.ts
Labels: patch, skip-release

#298 fix(busy-indicator): fixed various accessibility issues
  src/lib/busy-indicator/_mixins.scss
  src/lib/busy-indicator/busy-indicator.html
Labels: patch, skip-release

#306 fix(time-picker): improve input mask usability
  src/dev/pages/time-picker/time-picker.html
  src/lib/core/mask/intermediate-time-parser.ts
  src/lib/core/mask/time-input-mask.ts
  src/lib/core/mask/time-segment-parser.ts
  src/lib/core/utils/time-utils.ts
  src/lib/list-dropdown/list-dropdown-adapter.ts
  src/lib/list-dropdown/list-dropdown-constants.ts
  src/lib/list-dropdown/list-dropdown-foundation.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/time-picker/time-picker-adapter.ts
  src/lib/time-picker/time-picker-component-delegate.ts
  src/lib/time-picker/time-picker-foundation.ts
  src/lib/tooltip/tooltip-foundation.ts
  src/lib/tooltip/tooltip.ts
  src/test/spec/menu/menu.spec.ts
  src/test/spec/time-picker/time-picker.spec.ts
  src/test/spec/tooltip/tooltip.spec.ts
Labels: patch, skip-release, storybook-preview

#280 Feat/stack component
  src/dev/pages/stack/stack.ejs
  src/dev/pages/stack/stack.html
  src/dev/pages/stack/stack.scss
  src/dev/pages/stack/stack.ts
  src/dev/src/components.json
  src/lib/index.ts
  src/lib/stack/_mixins.scss
  src/lib/stack/_variables.scss
  src/lib/stack/index.ts
  src/lib/stack/stack-adapter.ts
  src/lib/stack/stack-constants.ts
  src/lib/stack/stack-foundation.ts
  src/lib/stack/stack.html
  src/lib/stack/stack.scss
  src/lib/stack/stack.ts
  src/test/spec/stack/stack.spec.ts
Labels: minor, skip-release, new component

#309 chore: update dependencies
  auto.config.ts
  package-lock.json
  package.json
Labels: skip-release

#307 fix: reference `@material/*` packages instead of `material-components-web` meta package to avoid dependency conflicts
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
Labels: minor

#312 feat(app-bar-profile-button): added new `avatarIcon` property to allow for rendering an icon from the `IconRegistry` instead of text
  src/lib/app-bar/profile-button/app-bar-profile-button-adapter.ts
  src/lib/app-bar/profile-button/app-bar-profile-button-constants.ts
  src/lib/app-bar/profile-button/app-bar-profile-button-foundation.ts
  src/lib/app-bar/profile-button/app-bar-profile-button.ts
  src/lib/profile-card/profile-card-adapter.ts
  src/lib/profile-card/profile-card-constants.ts
  src/lib/profile-card/profile-card-foundation.ts
  src/lib/profile-card/profile-card.ts
  src/stories/src/components/app-bar-profile/app-bar-profile-args.ts
  src/stories/src/components/app-bar-profile/app-bar-profile.mdx
  src/stories/src/components/app-bar-profile/app-bar-profile.stories.tsx
  src/test/spec/app-bar/profile-button/app-bar-profile-button.spec.ts
Labels: minor

#321 fix(stack): fix stretch styles
  src/lib/stack/_mixins.scss
  src/lib/stack/stack.scss
  src/stories/src/components/stack/stack.mdx
Labels: patch, skip-release
