Repository tyler-technologies-oss/forge, pull requests merged in 2023-06, with the labels that each got.

#319 fix(select): fixed a bug where filtering options with uppercase letters was not working
  src/lib/select/core/base-select-foundation.ts
  src/test/spec/select/select.spec.ts
Labels: patch, skip-release

#320 fix(select, autocomplete): show option label when one option is selected in multiple mode
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/select/core/base-select-foundation.ts
  src/test/spec/autocomplete/autocomplete.spec.ts
  src/test/spec/select/select.spec.ts
Labels: patch, skip-release

#318 fix(masks): time-picker, date-picker, date-range-picker > updates to mask behavior
  src/dev/pages/date-picker/date-picker.ejs
  src/dev/pages/date-range-picker/date-range-picker.ejs
  src/lib/chip-field/chip-field-foundation.ts
  src/lib/date-picker/base/base-date-picker-adapter.ts
  src/lib/date-picker/base/base-date-picker-foundation.ts
  src/lib/date-picker/date-picker-adapter.ts
  src/lib/date-range-picker/date-range-picker-adapter.ts
  src/lib/date-range-picker/date-range-picker-foundation.ts
  src/lib/field/field-adapter.ts
  src/lib/field/field-foundation.ts
  src/lib/text-field/text-field-adapter.ts
  src/lib/time-picker/time-picker-adapter.ts
  src/lib/time-picker/time-picker-foundation.ts
  src/stories/src/components/date-picker/date-picker.mdx
  src/stories/src/components/date-range-picker/date-range-picker.mdx
  src/stories/src/components/time-picker/time-picker.mdx
  src/test/spec/date-picker/date-picker.spec.ts
  src/test/spec/date-range-picker/date-range-component-delegate.spec.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
  src/test/spec/time-picker/time-picker.spec.ts
Labels: patch, skip-release

#313 feat(autocomplete): add `filterFocusFirst` property
  src/dev/pages/autocomplete/autocomplete.html
  src/dev/pages/autocomplete/autocomplete.ts
  src/lib/autocomplete/autocomplete-constants.ts
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/autocomplete/autocomplete.ts
  src/stories/src/components/autocomplete/autocomplete-args.ts
  src/stories/src/components/autocomplete/autocomplete.mdx
  src/stories/src/components/autocomplete/autocomplete.stories.tsx
  src/test/spec/autocomplete/autocomplete.spec.ts
Labels: minor, skip-release

#325 fix(date-picker): always dispatch the change event when a valid date is entered if `allowInvalidDate` is `true`
  src/lib/date-picker/base/base-date-picker-foundation.ts
  src/test/spec/date-picker/date-picker.spec.ts
Labels: patch, skip-release

#328 fix(split-view): query only immediate child panels
  src/lib/split-view/split-view/split-view-adapter.ts
  src/test/spec/split-view/split-view/split-view.spec.ts
Labels: bug, patch

#323 feat(circular-progress): refactor to remove MDC
  .autorc
  .eslintrc.json
  .github/workflows/build-release.yml
  .gitignore
  auto.config.ts
  forge.json
  package-lock.json
  package.json
  src/dev/pages/circular-progress/circular-progress.ejs
  src/dev/pages/circular-progress/circular-progress.html
  src/dev/pages/circular-progress/circular-progress.ts
  src/lib/circular-progress/_determinate.html
  src/lib/circular-progress/_indeterminate.html
  src/lib/circular-progress/_keyframes.scss
  src/lib/circular-progress/_mixins.scss
  src/lib/circular-progress/_variables.scss
  src/lib/circular-progress/circular-progress-adapter.ts
  src/lib/circular-progress/circular-progress-constants.ts
  src/lib/circular-progress/circular-progress-foundation.ts
  src/lib/circular-progress/circular-progress.html
  src/lib/circular-progress/circular-progress.scss
  src/lib/circular-progress/circular-progress.test.ts
  src/lib/circular-progress/circular-progress.ts
  src/lib/core/base/base-component.ts
  src/lib/core/style-layer/circular-progress/_animations.scss
  src/lib/core/style-layer/circular-progress/_core.scss
  src/lib/core/style-layer/circular-progress/_variables.scss
  src/lib/core/style-layer/circular-progress/index.scss
  src/lib/core/style-layer/core/_config.scss
  src/lib/tsconfig-build.json
  src/stories/src/components/circular-progress/circular-progress.mdx
  src/test/spec/circular-progress/circular-progress.spec.ts
  tsconfig.json
  web-test-runner.config.mjs
Labels: minor, @next

#330 fix(autocomplete): fixed a bug where selecting appended options in multiple mode would incorrectly select the wrong options in the UI dropdown
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/list-dropdown/list-dropdown-adapter.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
  src/test/spec/select/select-dropdown.spec.ts
Labels: patch

#334 fix(text-to-color): convert text input to uppercase
  src/lib/utils/color-utils.ts
Labels: patch, skip-release

#333 fix(paginator): fixed a bug where the paginator was not reflecting the current page size after selection in the page size select
  src/lib/paginator/paginator-foundation.ts
  src/test/spec/paginator/paginator.spec.ts
Labels: patch

#331 [next] refactor linear progress
  .eslintrc.json
  package-lock.json
  package.json
  src/dev/pages/linear-progress/linear-progress.ejs
  src/dev/pages/linear-progress/linear-progress.html
  src/dev/pages/linear-progress/linear-progress.ts
  src/lib/circular-progress/_mixins.scss
  src/lib/circular-progress/_variables.scss
  src/lib/circular-progress/circular-progress-adapter.ts
  src/lib/circular-progress/circular-progress.scss
  src/lib/circular-progress/circular-progress.test.ts
  src/lib/core/style-layer/circular-progress/_animations.scss
  src/lib/core/style-layer/circular-progress/_core.scss
  src/lib/core/style-layer/linear-progress/_animations.scss
  src/lib/core/style-layer/linear-progress/_core.scss
  src/lib/core/style-layer/linear-progress/_variables.scss
  src/lib/core/style-layer/linear-progress/index.scss
  src/lib/linear-progress/_mixins.scss
  src/lib/linear-progress/_variables.scss
  src/lib/linear-progress/index.ts
  src/lib/linear-progress/linear-progress-adapter.ts
  src/lib/linear-progress/linear-progress-constants.ts
  src/lib/linear-progress/linear-progress-foundation.ts
  src/lib/linear-progress/linear-progress.html
  src/lib/linear-progress/linear-progress.scss
  src/lib/linear-progress/linear-progress.test.ts
  src/lib/linear-progress/linear-progress.ts
  src/lib/list-dropdown/list-dropdown-adapter.ts
  src/stories/src/components/linear-progress/code/linear-progress-buffer.ts
  src/stories/src/components/linear-progress/code/linear-progress-determinate.ts
  src/stories/src/components/linear-progress/code/linear-progress-indeterminate.ts
  src/stories/src/components/linear-progress/linear-progress.mdx
  src/test/spec/autocomplete/autocomplete.spec.ts
  src/test/spec/linear-progress/linear-progress.spec.ts
  src/test/spec/list-dropdown/list-dropdown-test-utils.ts
Labels: minor, @next
