Repository tyler-technologies-oss/forge, pull requests merged in 2023-02, with the labels that each got.

#215 fix(switch): fixed a bug where the UI could incorrectly reflect the component state
  src/lib/switch/switch.ts
  src/test/spec/switch/switch.spec.ts
Labels: skip-release

#220 fix(split-view): add overlay to body while dragging to prevent context loss
  src/lib/split-view/split-view-panel/split-view-panel-adapter.ts
  src/lib/split-view/split-view-panel/split-view-panel-constants.ts
  src/lib/split-view/split-view-panel/split-view-panel-foundation.ts
  src/lib/split-view/split-view-panel/split-view-panel-utils.ts
  src/lib/split-view/split-view/split-view-constants.ts
  src/test/spec/split-view/split-view-panel/split-view-panel.spec.ts
Labels: patch

#222 fix(field): fixed a bug where height of helper-text element was incorrect
  src/lib/field/_base.scss
  src/lib/field/_variables.scss
Labels: skip-release

#226 fix(date-range-picker): fixed a bug that allowed invalid date ranges
  src/lib/date-range-picker/date-range-picker-foundation.ts
Labels: skip-release

#225 fix(list-item): fixed a bug where the UI could incorrectly reflect the component state
  src/lib/list/list-item/list-item-adapter.ts
  src/lib/list/list-item/list-item-foundation.ts
  src/lib/list/list-item/list-item.ts
  src/test/spec/list/list-item/list-item.spec.ts
Labels: patch

#231 perf(list-item): delay ripple creation
  src/lib/list/list-item/list-item-adapter.ts
  src/lib/list/list-item/list-item-foundation.ts
  src/test/spec/list/list-item/list-item.spec.ts
Labels: patch, performance

#233 bug: number pad enter for time-picker
  src/lib/list-dropdown/list-dropdown-foundation.ts
  src/lib/time-picker/time-picker-foundation.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
  src/test/spec/time-picker/time-picker.spec.ts
Labels: bug, patch

#236 fix(date-picker): fixed a bug where a 4-digit year was not correctly being masked with a leading 0
  src/lib/core/utils/date-utils.ts
Labels: skip-release

#237 chore: separate temp storybook deployment from build-pr workflow
  .github/workflows/build-pr.yml
  .github/workflows/build-release.yml
  .github/workflows/deploy-pr.yml
Labels: skip-release
