Repository tyler-technologies-oss/forge, pull requests merged in 2023-10, with the labels that each got.

#398 fix(paginator): fixed a bug where focus was lost when disabling the page buttons dynamically
  src/lib/paginator/paginator-adapter.ts
  src/test/spec/paginator/paginator.spec.ts
Labels: patch

#382 feat(switch): refactor switch component
  package-lock.json
  package.json
  src/dev/pages/switch/switch.ejs
  src/dev/pages/switch/switch.scss
  src/dev/pages/switch/switch.ts
  src/lib/core/base/base-component.ts
  src/lib/core/styles/tokens/switch/_tokens.scss
  src/lib/core/styles/tokens/theme/_tokens.scss
  src/lib/core/utils/a11y-utils.ts
  src/lib/core/utils/index.ts
  src/lib/core/utils/utils.ts
  src/lib/switch/_configuration.scss
  src/lib/switch/_core.scss
  src/lib/switch/_switch-mixins.scss
  src/lib/switch/_switch-theme.scss
  src/lib/switch/index.scss
  src/lib/switch/switch-adapter.ts
  src/lib/switch/switch-component-delegate.ts
  src/lib/switch/switch-constants.ts
  src/lib/switch/switch-foundation.ts
  src/lib/switch/switch.html
  src/lib/switch/switch.scss
  src/lib/switch/switch.test.ts
  src/lib/switch/switch.ts
  src/lib/theme/_theme-dark.scss
  src/test/spec/switch/switch-attributes.fixture.html
  src/test/spec/switch/switch-no-input.fixture.html
  src/test/spec/switch/switch.fixture.html
  src/test/spec/switch/switch.spec.ts
Labels: minor, @next

#326 feat(button-area): create button area component
  src/dev/pages/button-area/button-area.ejs
  src/dev/pages/button-area/button-area.html
  src/dev/pages/button-area/button-area.scss
  src/dev/pages/button-area/button-area.ts
  src/dev/src/components.json
  src/lib/button-area/_mixins.scss
  src/lib/button-area/button-area-adapter.ts
  src/lib/button-area/button-area-constants.ts
  src/lib/button-area/button-area-foundation.ts
  src/lib/button-area/button-area.html
  src/lib/button-area/button-area.scss
  src/lib/button-area/button-area.ts
  src/lib/button-area/index.ts
  src/lib/index.ts
  src/stories/src/components/button-area/button-area-args.ts
  src/stories/src/components/button-area/button-area.mdx
  src/stories/src/components/button-area/button-area.stories.tsx
  src/stories/src/components/button-area/code/button-area-default.ts
  src/test/spec/button-area/button-area.spec.ts
Labels: enhancement, minor

#402 fix(paginator): fixed how `offset` updates `pageIndex` along with updates to focus management
  src/lib/paginator/paginator-adapter.ts
  src/lib/paginator/paginator-foundation.ts
  src/lib/paginator/paginator.ts
  src/test/spec/paginator/paginator.spec.ts
Labels: patch

#404 fix(text-field): fixed a bug where the label was not being initialized properly when toggling density dynamically
  src/lib/field/field-foundation.ts
  src/lib/floating-label/floating-label-foundation.ts
  src/lib/floating-label/floating-label.ts
  src/test/spec/text-field/text-field.spec.ts
  src/test/utils/floating-label-utils.ts
Labels: patch

#406 fix(expansion-panel): fixed a bug where calling `setOpenImmediate()` while an expand/collapse animation is already running would not cancel the active animation
  src/lib/expansion-panel/expansion-panel-adapter.ts
  src/test/spec/expansion-panel/expansion-panel.spec.ts
Labels: patch

#376 feat(list): refactored list components
  package-lock.json
  package.json
  src/dev/pages/list/list.ejs
  src/dev/pages/list/list.scss
  src/dev/pages/list/list.ts
  src/lib/calendar/calendar-menu/_mixins.scss
  src/lib/core/base/base-adapter.ts
  src/lib/core/keyboard/key-manager.ts
  src/lib/core/styles/_utils.scss
  src/lib/core/styles/tokens/focus-indicator/_tokens.scss
  src/lib/core/styles/tokens/list/list-item/_tokens.scss
  src/lib/core/styles/tokens/list/list/_tokens.scss
  src/lib/core/styles/tokens/state-layer/_tokens.scss
  src/lib/core/styles/typography/index.scss
  src/lib/core/utils/utils.ts
  src/lib/focus-indicator/focus-indicator-foundation.ts
  src/lib/index.ts
  src/lib/list-dropdown/list-dropdown-adapter.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/list/build.json
  src/lib/list/list-item/_configuration.scss
  src/lib/list/list-item/_core.scss
  src/lib/list/list-item/_mixins.scss
  src/lib/list/list-item/_variables.scss
  src/lib/list/list-item/index.scss
  src/lib/list/list-item/list-item-adapter.ts
  src/lib/list/list-item/list-item-constants.ts
  src/lib/list/list-item/list-item-foundation.ts
  src/lib/list/list-item/list-item.html
  src/lib/list/list-item/list-item.scss
  src/lib/list/list-item/list-item.ts
  src/lib/list/list.test.ts
  src/lib/list/list/_configuration.scss
  src/lib/list/list/_core.scss
  src/lib/list/list/_mixins.scss
  src/lib/list/list/index.scss
  src/lib/list/list/index.ts
  src/lib/list/list/list-adapter.ts
  src/lib/list/list/list-constants.ts
  src/lib/list/list/list-foundation.ts
  src/lib/list/list/list.html
  src/lib/list/list/list.scss
  src/lib/list/list/list.ts
  src/lib/slider/_core.scss
  src/lib/slider/slider.html
  src/lib/slider/slider.test.ts
  src/lib/tabs/tab/tab.html
  src/test/spec/autocomplete/autocomplete.spec.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
  src/test/spec/list/list-item/list-item.spec.ts
  src/test/spec/list/list/list.spec.ts
  src/test/spec/menu/menu.spec.ts
  src/test/spec/paginator/paginator.spec.ts
  src/test/spec/select/select.spec.ts
  src/test/spec/time-picker/time-picker.spec.ts
Labels: minor

#417 chore(theme): refactor theme tokens
  src/dev/pages/theme/theme.ejs
  src/dev/pages/theme/theme.html
  src/dev/pages/theme/theme.scss
  src/dev/pages/theme/theme.ts
  src/dev/src/components.json
  src/dev/src/styles/_header.scss
  src/dev/src/styles/_options.scss
  src/lib/core/styles/_utils.scss
  src/lib/core/styles/scrollbar/index.scss
  src/lib/core/styles/spacing/index.scss
  src/lib/core/styles/theme/_color-utils.scss
  src/lib/core/styles/theme/_utils.scss
  src/lib/core/styles/theme/index.scss
  src/lib/core/styles/tokens/circular-progress/_tokens.scss
  src/lib/core/styles/tokens/color-palette/_extended-color-palette.scss
  src/lib/core/styles/tokens/color-palette/_material-color-palette.scss
  src/lib/core/styles/tokens/color-palette/index.scss
  src/lib/core/styles/tokens/focus-indicator/_tokens.scss
  src/lib/core/styles/tokens/linear-progress/_tokens.scss
  src/lib/core/styles/tokens/list/list-item/_tokens.scss
  src/lib/core/styles/tokens/scrollbar/_tokens.scss
  src/lib/core/styles/tokens/slider/_tokens.scss
  src/lib/core/styles/tokens/spacing/_tokens.scss
  src/lib/core/styles/tokens/switch/_tokens.scss
  src/lib/core/styles/tokens/tabs/tab-bar/_tokens.scss
  src/lib/core/styles/tokens/tabs/tab/_tokens.scss
  src/lib/core/styles/tokens/theme/_color-emphasis.scss
  src/lib/core/styles/tokens/theme/_token-utils.scss
  src/lib/core/styles/tokens/theme/_tokens.core.scss
  src/lib/core/styles/tokens/theme/_tokens.scss
  src/lib/core/styles/tokens/theme/_tokens.status.scss
  src/lib/core/styles/tokens/theme/_tokens.surface.scss
  src/lib/core/styles/tokens/theme/_tokens.text.scss
  src/lib/core/styles/tokens/theme/_tokens.utilities.scss
  src/lib/core/styles/tokens/typography/_tokens.scss
  src/lib/slider/_core.scss
  src/lib/slider/slider.scss
  src/lib/tabs/tab/_configuration.scss
  src/lib/tabs/tab/_core.scss
  src/lib/tabs/tab/tab.scss
  src/lib/theme/_theme.scss
  src/lib/theme/forge-theme.scss
Labels: minor

#416 fix(table): sortable column headers will now use `<button>` element for a11y purposes
  src/lib/table/_mixins.scss
  src/lib/table/table-foundation.ts
  src/lib/table/table-utils.ts
  src/lib/table/types.ts
  src/test/spec/table/table.spec.ts
Labels: patch, accessibility

#415 fix(paginator): fix focus management to properly account for state updates while the element is already focused
  src/lib/paginator/paginator-adapter.ts
  src/lib/paginator/paginator-foundation.ts
  src/lib/paginator/paginator.ts
  src/test/spec/paginator/paginator.spec.ts
Labels: patch

#408 feat(chip field): add member on blur
  src/dev/pages/chip-field/chip-field.html
  src/dev/pages/chip-field/chip-field.ts
  src/lib/chip-field/chip-field-constants.ts
  src/lib/chip-field/chip-field-foundation.ts
  src/lib/chip-field/chip-field.ts
  src/lib/field/field-constants.ts
  src/stories/src/components/chip-field/chip-field-args.ts
  src/stories/src/components/chip-field/chip-field.mdx
  src/stories/src/components/chip-field/chip-field.stories.tsx
  src/test/spec/chip-field/chip-field.spec.ts
Labels: enhancement, minor, feature request

#409 feat(checkbox): refactor checkbox component
  src/dev/pages/checkbox/checkbox.ejs
  src/dev/pages/checkbox/checkbox.html
  src/dev/pages/checkbox/checkbox.ts
  src/dev/pages/switch/switch.ejs
  src/dev/pages/switch/switch.ts
  src/lib/checkbox/_checkbox-custom-properties.scss
  src/lib/checkbox/_checkbox-theme.scss
  src/lib/checkbox/_checkbox.mixins.scss
  src/lib/checkbox/_configuration.scss
  src/lib/checkbox/_core.scss
  src/lib/checkbox/checkbox-adapter.ts
  src/lib/checkbox/checkbox-component-delegate.ts
  src/lib/checkbox/checkbox-constants.ts
  src/lib/checkbox/checkbox-foundation.ts
  src/lib/checkbox/checkbox.html
  src/lib/checkbox/checkbox.scss
  src/lib/checkbox/checkbox.test.ts
  src/lib/checkbox/checkbox.ts
  src/lib/checkbox/index.scss
  src/lib/checkbox/index.ts
  src/lib/core/base/base-adapter.ts
  src/lib/core/base/base-component.ts
  src/lib/core/styles/tokens/checkbox/_tokens.scss
  src/lib/core/styles/tokens/switch/_tokens.scss
  src/lib/core/utils/a11y-utils.ts
  src/lib/core/utils/index.ts
  src/lib/core/utils/reflect-utils.ts
  src/lib/focus-indicator/focus-indicator-adapter.ts
  src/lib/focus-indicator/focus-indicator-foundation.ts
  src/lib/list/list/list-adapter.ts
  src/lib/slider/slider.html
  src/lib/state-layer/state-layer-foundation.ts
  src/lib/switch/_configuration.scss
  src/lib/switch/_core.scss
  src/lib/switch/index.ts
  src/lib/switch/switch-adapter.ts
  src/lib/switch/switch-component-delegate.ts
  src/lib/switch/switch-constants.ts
  src/lib/switch/switch-foundation.ts
  src/lib/switch/switch.html
  src/lib/switch/switch.scss
  src/lib/switch/switch.test.ts
  src/lib/switch/switch.ts
  src/test/spec/checkbox/checkbox-checked.fixture.html
  src/test/spec/checkbox/checkbox-no-input.html
  src/test/spec/checkbox/checkbox.fixture.html
  src/test/spec/checkbox/checkbox.spec.ts
Labels: minor, @next

#410 feat(label): create label component
  src/dev/pages/label/label.ejs
  src/dev/pages/label/label.html
  src/dev/pages/label/label.scss
  src/dev/pages/label/label.ts
  src/dev/src/components.json
  src/lib/checkbox/checkbox-adapter.ts
  src/lib/checkbox/checkbox-foundation.ts
  src/lib/checkbox/checkbox.ts
  src/lib/core/styles/tokens/label/_tokens.scss
  src/lib/index.ts
  src/lib/label/_core.scss
  src/lib/label/build.json
  src/lib/label/index.scss
  src/lib/label/index.ts
  src/lib/label/label-adapter.ts
  src/lib/label/label-aware.ts
  src/lib/label/label-constants.ts
  src/lib/label/label-foundation.ts
  src/lib/label/label.html
  src/lib/label/label.scss
  src/lib/label/label.test.ts
  src/lib/label/label.ts
  src/lib/switch/switch-adapter.ts
  src/lib/switch/switch-foundation.ts
  src/lib/switch/switch.ts
Labels: enhancement, minor, @next
