Repository tyler-technologies-oss/forge, pull requests merged in 2023-08, with the labels that each got.

#355 fix: fixed a bug where detecting the active element after being adopted into a new document could incorrectly reflect the wrong element
  package-lock.json
  package.json
  src/lib/app-bar/profile-button/app-bar-profile-button-adapter.ts
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/busy-indicator/busy-indicator-adapter.ts
  src/lib/chip-field/chip-field-foundation.ts
  src/lib/chips/chip/chip-adapter.ts
  src/lib/date-picker/date-picker-adapter.ts
  src/lib/date-range-picker/date-range-picker-adapter.ts
  src/lib/dialog/dialog-adapter.ts
  src/lib/field/field-adapter.ts
  src/lib/list/list/list-adapter.ts
  src/lib/popup/popup-adapter.ts
  src/lib/radio/radio-adapter.ts
  src/lib/stepper/stepper/stepper-adapter.ts
  src/lib/tabs/tab-bar/tab-bar-adapter.ts
  src/lib/text-field/text-field-adapter.ts
  src/lib/time-picker/time-picker-adapter.ts
Labels: patch

#358 fix(list-item): fixed a bug where setting `dense` wasn't applying the correct height
  src/lib/list/list-item/_mixins.scss
  src/lib/list/list-item/_variables.scss
Labels: patch

#362 feat(tokens): initial foundation for supporting global tokens
  src/dev/pages/circular-progress/circular-progress.ejs
  src/dev/pages/focus-indicator/focus-indicator.ejs
  src/dev/pages/typography/typography.ejs
  src/dev/pages/typography/typography.ts
  src/dev/src/component-list.ts
  src/dev/src/partials/controls/radiogroup.ejs
  src/dev/src/partials/page.ejs
  src/dev/src/shared.ts
  src/lib/circular-progress/_animation.scss
  src/lib/circular-progress/_configuration.scss
  src/lib/circular-progress/_core.scss
  src/lib/circular-progress/circular-progress.scss
  src/lib/circular-progress/index.scss
  src/lib/core/styles/_utils.scss
  src/lib/core/styles/animation/index.scss
  src/lib/core/styles/border/index.scss
  src/lib/core/styles/elevation/index.scss
  src/lib/core/styles/shape/index.scss
  src/lib/core/styles/spacing/index.scss
  src/lib/core/styles/theme/index.scss
  src/lib/core/styles/tokens/animation/_tokens.scss
  src/lib/core/styles/tokens/border/_tokens.scss
  src/lib/core/styles/tokens/circular-progress/_tokens.scss
  src/lib/core/styles/tokens/elevation/_tokens.scss
  src/lib/core/styles/tokens/focus-indicator/_tokens.scss
  src/lib/core/styles/tokens/linear-progress/_tokens.scss
  src/lib/core/styles/tokens/shape/_tokens.scss
  src/lib/core/styles/tokens/slider/_tokens.scss
  src/lib/core/styles/tokens/spacing/_tokens.scss
  src/lib/core/styles/tokens/state-layer/_tokens.scss
  src/lib/core/styles/tokens/tabs/tab-bar/_tokens.scss
  src/lib/core/styles/tokens/tabs/tab/_tokens.scss
  src/lib/core/styles/tokens/theme/_shape.scss
  src/lib/core/styles/tokens/typography/_tokens.scss
  src/lib/core/styles/typography/index.scss
  src/lib/focus-indicator/_core.scss
  src/lib/linear-progress/_core.scss
  src/lib/slider/_configuration.scss
  src/lib/slider/_core.scss
  src/lib/slider/slider.ts
  src/lib/state-layer/_core.scss
  src/lib/table/_mixins.scss
  src/lib/tabs/tab-bar/_core.scss
  src/lib/tabs/tab/_core.scss
  src/lib/tabs/tab/tab.scss
  src/lib/typography/build.json
  src/lib/typography/forge-form.scss
  src/lib/typography/forge-typography-legacy.scss
  src/lib/typography/forge-typography.scss
  src/lib/utils/_mixins-core.scss
  src/stories/src/components/slider/slider.mdx
Labels: minor, @next

#365 feat(popup): add popup ref to close event, emit from host
  src/lib/popup/popup-adapter.ts
  src/lib/popup/popup-foundation.ts
  src/lib/popup/popup.ts
  src/stories/src/components/popup/popup.mdx
  src/test/spec/popup/popup.spec.ts
Labels: minor

#367 feat(keyboard-shortcut): add activate callback
  src/lib/keyboard-shortcut/keyboard-shortcut-constants.ts
  src/lib/keyboard-shortcut/keyboard-shortcut-foundation.ts
  src/lib/keyboard-shortcut/keyboard-shortcut.ts
  src/stories/src/components/keyboard-shortcut/keyboard-shortcut.mdx
  src/test/spec/keyboard-shortcut/keyboard-shortcut.spec.ts
Labels: enhancement, minor
