Repository tyler-technologies-oss/forge, pull requests merged in 2023-12, with the labels that each got.

#442 [@next] refactor button toggle
  src/dev/pages/button-toggle/button-toggle.ejs
  src/dev/pages/button-toggle/button-toggle.html
  src/dev/pages/button-toggle/button-toggle.scss
  src/dev/pages/button-toggle/button-toggle.ts
  src/lib/app-bar/app-bar/app-bar.test.ts
  src/lib/button-toggle/build.json
  src/lib/button-toggle/button-toggle-group/_core.scss
  src/lib/button-toggle/button-toggle-group/_mixins.scss
  src/lib/button-toggle/button-toggle-group/_token-utils.scss
  src/lib/button-toggle/button-toggle-group/button-toggle-group-adapter.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group-constants.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group-foundation.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group.html
  src/lib/button-toggle/button-toggle-group/button-toggle-group.scss
  src/lib/button-toggle/button-toggle-group/button-toggle-group.ts
  src/lib/button-toggle/button-toggle-group/index.scss
  src/lib/button-toggle/button-toggle.test.ts
  src/lib/button-toggle/button-toggle/_core.scss
  src/lib/button-toggle/button-toggle/_mixins.scss
  src/lib/button-toggle/button-toggle/_token-utils.scss
  src/lib/button-toggle/button-toggle/button-toggle-adapter.ts
  src/lib/button-toggle/button-toggle/button-toggle-constants.ts
  src/lib/button-toggle/button-toggle/button-toggle-foundation.ts
  src/lib/button-toggle/button-toggle/button-toggle.html
  src/lib/button-toggle/button-toggle/button-toggle.scss
  src/lib/button-toggle/button-toggle/button-toggle.ts
  src/lib/button-toggle/button-toggle/index.scss
  src/lib/calendar/calendar-foundation.ts
  src/lib/core/base/base-form-associated-component.ts
  src/lib/core/base/base-nullable-form-component.ts
  src/lib/core/mixins/form/with-validity.ts
  src/lib/core/styles/tokens/button-toggle/button-toggle-group/_tokens.scss
  src/lib/core/styles/tokens/button-toggle/button-toggle/_tokens.scss
  src/lib/core/utils/form-utils.ts
  src/lib/label/label-adapter.ts
  src/lib/label/label-constants.ts
  src/test/spec/button-toggle/button-toggle.fixture.html
  src/test/spec/button-toggle/button-toggle.spec.ts
  src/test/spec/date-picker/date-picker.spec.ts
Labels: minor, @next

#444 [@next] general cleanup, fixes, and organization
  src/dev/pages/card/card.ts
  src/dev/pages/chips/chips.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group-constants.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group.ts
  src/lib/button-toggle/button-toggle.test.ts
  src/lib/button-toggle/button-toggle/button-toggle-constants.ts
  src/lib/button-toggle/button-toggle/button-toggle.ts
  src/lib/button/base/base-button.ts
  src/lib/constants.ts
  src/lib/core/base/base-element-internals-component.test.ts
  src/lib/core/base/base-form-associated-component.test.ts
  src/lib/core/base/base-label-aware-component.test.ts
  src/lib/core/base/index.ts
  src/lib/core/mixins/focus/with-focusable.test.ts
  src/lib/core/mixins/focus/with-focusable.ts
  src/lib/core/mixins/form/with-form-associated.ts
  src/lib/core/mixins/form/with-form-validity.ts
  src/lib/core/mixins/internals/with-default-aria.ts
  src/lib/core/mixins/internals/with-element-internals.ts
  src/lib/core/mixins/label/with-label-aware.ts
  src/lib/core/styles/tokens/_token-utils.scss
  src/lib/core/styles/tokens/button-toggle/button-toggle-group/_tokens.scss
  src/lib/core/styles/tokens/button-toggle/button-toggle/_tokens.scss
  src/lib/core/styles/tokens/button/_tokens.scss
  src/lib/core/styles/tokens/checkbox/_tokens.scss
  src/lib/core/styles/tokens/floating-action-button/_tokens.scss
  src/lib/core/styles/tokens/icon-button/_tokens.scss
  src/lib/core/styles/tokens/profile-card/_tokens.scss
  src/lib/core/styles/tokens/radio/_tokens.scss
  src/lib/core/styles/tokens/switch/_tokens.scss
  src/lib/core/styles/tokens/tabs/tab/_tokens.scss
  src/lib/core/styles/tokens/theme/_tokens.utilities.scss
  src/lib/radio/radio-group/radio-group.ts
  src/lib/radio/radio/radio.ts
Labels: skip-release, @next

#443 fix(expansion-panel): remove invalid `aria-expanded` attribute set on header
  src/lib/calendar/calendar-foundation.ts
  src/lib/expansion-panel/expansion-panel-adapter.ts
  src/test/spec/date-picker/date-picker.spec.ts
Labels: patch, accessibility

#446 fix(date-range-picker): fixed a bug where the "to" value was not being rendered in `<input>` when initialized with a default value
  src/lib/date-range-picker/date-range-picker-foundation.ts
  src/test/spec/date-range-picker/date-range-component-delegate.spec.ts
Labels: patch

#445 [@next] refactor `setDefaultAria` to use `ElementInternals` as fallback
  package-lock.json
  package.json
  src/dev/pages/button-toggle/button-toggle.ejs
  src/dev/pages/button-toggle/button-toggle.html
  src/dev/pages/button-toggle/button-toggle.scss
  src/dev/pages/theme/theme.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group-constants.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group-foundation.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group.scss
  src/lib/button-toggle/button-toggle-group/button-toggle-group.ts
  src/lib/button-toggle/button-toggle.test.ts
  src/lib/button-toggle/button-toggle/button-toggle-adapter.ts
  src/lib/button-toggle/button-toggle/button-toggle-constants.ts
  src/lib/button-toggle/button-toggle/button-toggle.scss
  src/lib/button-toggle/button-toggle/button-toggle.ts
  src/lib/button/base/base-button-adapter.ts
  src/lib/button/base/base-button-constants.ts
  src/lib/button/base/base-button-foundation.ts
  src/lib/button/base/base-button.ts
  src/lib/circular-progress/circular-progress-adapter.ts
  src/lib/circular-progress/circular-progress.scss
  src/lib/circular-progress/circular-progress.test.ts
  src/lib/circular-progress/circular-progress.ts
  src/lib/constants.ts
  src/lib/core/mixins/internals/with-default-aria.ts
  src/lib/core/styles/tokens/button-toggle/button-toggle-group/_tokens.scss
  src/lib/core/styles/tokens/button-toggle/button-toggle/_tokens.scss
  src/lib/core/styles/tokens/theme/_token-utils.scss
  src/lib/core/styles/tokens/theme/_tokens.text.scss
  src/lib/core/utils/a11y-utils.ts
  src/lib/core/utils/feature-detection.ts
  src/lib/expansion-panel/expansion-panel-adapter.ts
  src/lib/linear-progress/linear-progress-adapter.ts
  src/lib/linear-progress/linear-progress-constants.ts
  src/lib/linear-progress/linear-progress-foundation.ts
  src/lib/linear-progress/linear-progress.ts
  src/lib/radio/core/radio-group-manager.ts
  src/lib/radio/radio-group/radio-group-adapter.ts
  src/lib/radio/radio-group/radio-group-constants.ts
  src/lib/radio/radio-group/radio-group.ts
  src/lib/radio/radio/radio-adapter.ts
  src/lib/radio/radio/radio-constants.ts
  src/lib/radio/radio/radio.ts
Labels: skip-release, @next
