Repository tyler-technologies-oss/forge, pull requests merged in 2024-08, with the labels that each got.

#663 chore: add `generate:component` npm script for scaffolding a new component
  .eslintrc.json
  .prettierignore
  package-lock.json
  package.json
  plopfile.mjs
  templates/component-base/index.ts.hbs
  templates/component-base/{{dashCase name}}-constants.ts.hbs
  templates/component-core-adapter/{{dashCase name}}-adapter.ts.hbs
  templates/component-core-adapter/{{dashCase name}}-core.ts.hbs
  templates/component-core-adapter/{{dashCase name}}.ts.hbs
  templates/component-lite/component.ts.hbs
  templates/component-styles/_core.scss.hbs
  templates/component-styles/index.scss.hbs
  templates/component-styles/{{dashCase name}}.scss.hbs
  templates/component-template/{{dashCase name}}.html.hbs
  templates/component-test/{{dashCase name}}.test.ts.hbs
  templates/demo/{{dashCase name}}.ejs.hbs
  templates/demo/{{dashCase name}}.html.hbs
  templates/demo/{{dashCase name}}.ts.hbs
  templates/storybook/{{pascalCase name}}.mdx.hbs
  templates/storybook/{{pascalCase name}}.stories.ts.hbs
  templates/tokens/_token-utils.scss.hbs
  templates/tokens/_tokens.scss.hbs
Labels: skip-release

#665 feat(skip-link): add inline variant and style tweaks
  src/dev/pages/skip-link/skip-link.ejs
  src/lib/core/styles/tokens/skip-link/_tokens.scss
  src/lib/skip-link/_core.scss
  src/lib/skip-link/skip-link-constants.ts
  src/lib/skip-link/skip-link.scss
  src/lib/skip-link/skip-link.test.ts
  src/lib/skip-link/skip-link.ts
  src/stories/components/skip-link/SkipLink.mdx
  src/stories/components/skip-link/SkipLink.stories.ts
Labels: minor, skip-release

#666 fix(field): reduce font size when dense/extra-small
  src/dev/index.ejs
  src/dev/src/component-list.ts
  src/lib/core/styles/tokens/field/_tokens.scss
  src/lib/core/styles/tokens/select/_tokens.scss
  src/lib/core/styles/tokens/typography/_scale.scss
  src/lib/core/styles/typography/index.scss
  src/lib/field/_core.slotted.scss
  src/lib/field/field.scss
  src/lib/select/select/_core.scss
  src/lib/select/select/select.scss
  src/lib/select/select/select.ts
Labels: patch, skip-release

#667 fix(button-toggle): relax the generic type on the event data interfaces to `any`
  src/lib/button-toggle/button-toggle-group/button-toggle-group-constants.ts
  src/lib/button-toggle/button-toggle/button-toggle-constants.ts
Labels: patch, skip-release

#673 chore: updated `@tylertech-eslint/eslint-plugin` to latest
  package-lock.json
  package.json
  src/lib/core/mask/intermediate-time-parser.ts
  src/lib/split-button/split-button-core.ts
Labels: skip-release

#678 fix(checkbox, radio, switch, field): remove opacity on field labels when disabled
  src/lib/checkbox/checkbox.scss
  src/lib/field/_core.scss
  src/lib/radio/radio/radio.scss
  src/lib/switch/switch.scss
Labels: patch, skip-release

#677 docs(menu): add note/code snippet about using JS to set options
  src/stories/components/menu/Menu.mdx
Labels: documentation, skip-release

#676 fix(app-bar): add "custom" to `AppBarTheme` type to fix typings compatibility with docs
  src/lib/app-bar/app-bar/app-bar-constants.ts
Labels: patch, skip-release

#674 feat: allow for `variant` property on field, text-field, and select to be globally configurable
  src/lib/field/field-core.ts
  src/lib/field/field.ts
  src/lib/select/select/select-core.ts
  src/lib/select/select/select.ts
  src/lib/text-field/text-field-core.ts
  src/lib/text-field/text-field.ts
Labels: minor, skip-release

#672 fix(list): fix spacing token
  src/lib/list/list/_core.scss
  src/lib/list/list/list.scss
Labels: patch, skip-release
