Repository tyler-technologies-oss/forge, pull requests merged in 2024-11, with the labels that each got.

#739 fix(toolbar): fixed "after-section-end" part name
  src/lib/toolbar/toolbar.html
Labels: patch, skip-release

#738 fix(chip-field): fixed a bug where the dropdown would close immediately if clicking directly on the `<input>` element
  src/lib/chip-field/chip-field-adapter.ts
  src/lib/chip-field/chip-field-core.ts
Labels: patch, skip-release

#737 docs(FAQ): added a new FAQ page describing how to handle focus indicator clipping
  .storybook/preview.ts
  src/stories/faq/FocusIndicatorClipping.mdx
  src/stories/faq/FocusIndicatorClipping.stories.ts
Labels: documentation, skip-release

#732 fix(TextFieldComponentDelegate): fix duplicate `id` being set when provided via options
  src/lib/text-field/text-field-component-delegate.ts
Labels: patch, skip-release

#731 fix(field): hide required asterisk at extra-small density
  src/lib/field/field.scss
Labels: patch, skip-release

#730 fix(field): fixed a bug where the width could collapse while the inset label animation is executing
  src/lib/field/field-adapter.ts
  src/lib/field/field-constants.ts
Labels: patch, skip-release

#736 fix: allow overflowing content in card, scaffold, and expansion panel
  src/lib/core/styles/tokens/card/_tokens.scss
  src/lib/core/styles/tokens/scaffold/_tokens.scss
  src/lib/expansion-panel/_core.scss
  src/lib/expansion-panel/expansion-panel-adapter.ts
  src/lib/expansion-panel/expansion-panel-constants.ts
  src/lib/expansion-panel/expansion-panel-core.ts
  src/lib/expansion-panel/expansion-panel.scss
  src/lib/expansion-panel/forge-expansion-panel.scss
  src/lib/scaffold/_core.scss
  src/lib/scaffold/forge-scaffold.scss
Labels: patch, skip-release

#733 fix(accordion): always dispatch `forge-expansion-panel-toggle` event on panels that are closing in response to a user toggling another panel
  src/lib/accordion/accordion-constants.ts
  src/lib/accordion/accordion-core.ts
  src/lib/accordion/accordion.test.ts
  src/lib/accordion/accordion.ts
  src/lib/expansion-panel/expansion-panel-constants.ts
  src/lib/expansion-panel/expansion-panel-core.ts
  src/lib/expansion-panel/expansion-panel.test.ts
  src/lib/expansion-panel/expansion-panel.ts
Labels: patch

#740 fix(popover): gracefully handle how popovers are positioned when their dimensions are clipped by the viewport to ensure access to the content
  src/lib/list-dropdown/list-dropdown-adapter.ts
  src/lib/overlay/overlay-adapter.ts
  src/lib/overlay/overlay-constants.ts
  src/lib/popover/popover.scss
Labels: patch, skip-release

#744 fix(text-field): fixed a bug where the input container would lock its width if there is no floating label to animate
  src/lib/field/field-adapter.ts
  src/lib/field/field-constants.ts
  src/lib/field/field-core.ts
  src/lib/field/field.test.ts
Labels: patch

#747 fix(field): set `aria-hidden="true"` on popover icon `<svg>`
  src/lib/field/field.html
Labels: patch, skip-release

#746 fix(autocomplete): preventDefault on popover-icon mousedown instead of click
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/field/field-adapter.ts
  src/lib/field/field-constants.ts
  src/lib/field/field-core.ts
  src/lib/field/field.test.ts
  src/lib/field/field.ts
  src/test/spec/autocomplete/autocomplete.spec.ts
Labels: patch, skip-release

#748 fix(time-picker): gracefully handle input element reference being undefined
  src/lib/time-picker/time-picker-adapter.ts
  src/lib/time-picker/time-picker-core.ts
Labels: patch, skip-release

#760 fix(popover): fixed a bug where the popover would stay connected if hidden at time of exit animation
  src/lib/calendar/calendar-dropdown/calendar-dropdown.ts
  src/lib/popover/popover-adapter.ts
Labels: patch, skip-release

#763 fix(field): fix input size/animation when floating label with inset variant
  src/dev/pages/text-field/text-field.ts
  src/lib/field/_core.animation.scss
  src/lib/field/_core.layout.scss
  src/lib/field/_core.slotted.scss
  src/lib/field/field-adapter.ts
  src/lib/field/field.scss
  src/lib/field/field.test.ts
Labels: patch, skip-release

#764 docs: upgrade Storybook and other dependencies
  .storybook/main.ts
  package-lock.json
  package.json
  plugins/cem/filter-ignored.mjs
  src/lib/core/styles/_utils.scss
  src/lib/core/styles/theme/_utils.scss
  src/lib/core/styles/tokens/list/list/_tokens.scss
  src/lib/radio/index.scss
  src/stories/components/skip-link/SkipLink.stories.ts
  src/stories/getting-started/CSSOnlyComponents.mdx
Labels: documentation, skip-release

#757 perf: update forge-core to optimize attachShadowTemplate
  package-lock.json
  package.json
Labels: patch

#762 fix(select): elementAttributes are now applied to select options
  src/lib/select/core/base-select-adapter.ts
  src/test/spec/select/select.spec.ts
Labels: patch, @2.x
