Repository tyler-technologies-oss/forge, pull requests merged in 2024-03, with the labels that each got.

#490 Next page state
  src/lib/core/styles/tokens/page-state/_tokens.scss
  src/lib/page-state/_core.scss
  src/lib/page-state/_mixins.scss
  src/lib/page-state/_token-utils.scss
  src/lib/page-state/_variables.scss
  src/lib/page-state/index.scss
  src/lib/page-state/page-state.html
  src/lib/page-state/page-state.scss
  src/lib/page-state/page-state.test.ts
  src/lib/utils/_mixins-container.scss
  src/test/spec/page-state/page-state.spec.ts
Labels: minor, skip-release, @next

#489 [@next][button-area] refactor to use tokens, state-layer, and focus-indicator
  src/lib/button-area/_core.scss
  src/lib/button-area/_mixins.scss
  src/lib/button-area/_token-utils.scss
  src/lib/button-area/button-area-adapter.ts
  src/lib/button-area/button-area-constants.ts
  src/lib/button-area/button-area-foundation.ts
  src/lib/button-area/button-area.html
  src/lib/button-area/button-area.scss
  src/lib/button-area/button-area.test.ts
  src/lib/button-area/button-area.ts
  src/lib/button-area/index.scss
  src/lib/card/_mixins.scss
  src/lib/core/styles/tokens/button-area/_tokens.scss
  src/lib/expansion-panel/_mixins.scss
  src/test/spec/button-area/button-area.spec.ts
Labels: minor, skip-release, @next

#494 fix(page-state): include jsdocs
  src/lib/page-state/page-state.ts
Labels: patch, skip-release, @next

#492 Next file picker refactor
  src/dev/pages/file-picker/file-picker.ejs
  src/lib/core/styles/tokens/file-picker/_tokens.scss
  src/lib/file-picker/_core.scss
  src/lib/file-picker/_mixins.scss
  src/lib/file-picker/_token-utils.scss
  src/lib/file-picker/_variables.scss
  src/lib/file-picker/file-picker-adapter.ts
  src/lib/file-picker/file-picker.html
  src/lib/file-picker/file-picker.scss
  src/lib/file-picker/file-picker.test.ts
  src/lib/file-picker/file-picker.ts
  src/lib/file-picker/index.scss
  src/lib/toolbar/_core.scss
  src/test/spec/file-picker/file-picker.spec.ts
Labels: minor, skip-release, @next

#478 [@next][text-field] refactor to use field component
  src/dev/pages/field/field.ejs
  src/dev/pages/text-field/text-field.ejs
  src/dev/pages/text-field/text-field.html
  src/dev/pages/text-field/text-field.scss
  src/dev/pages/text-field/text-field.ts
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/button/base/base-button-adapter.ts
  src/lib/core/base/base-adapter.ts
  src/lib/core/styles/tokens/field/_tokens.scss
  src/lib/date-picker/base/base-date-picker-adapter.ts
  src/lib/date-picker/base/base-date-picker-utils.ts
  src/lib/date-range-picker/date-range-picker-adapter.ts
  src/lib/date-range-picker/date-range-picker-component-delegate.ts
  src/lib/field-next/_core.scss
  src/lib/field-next/_core.slotted.scss
  src/lib/field-next/base/base-field-adapter.ts
  src/lib/field-next/base/base-field-constants.ts
  src/lib/field-next/base/base-field-foundation.ts
  src/lib/field-next/base/base-field.test.ts
  src/lib/field-next/base/base-field.ts
  src/lib/field-next/base/index.ts
  src/lib/field-next/field-adapter.ts
  src/lib/field-next/field-constants.ts
  src/lib/field-next/field-foundation.ts
  src/lib/field-next/field.html
  src/lib/field-next/field.scss
  src/lib/field-next/field.test.ts
  src/lib/field-next/field.ts
  src/lib/field-next/index.ts
  src/lib/label/label-foundation.ts
  src/lib/label/label.ts
  src/lib/text-field/_base.scss
  src/lib/text-field/_core.scss
  src/lib/text-field/_mixins.scss
  src/lib/text-field/_selector.scss
  src/lib/text-field/_variables.scss
  src/lib/text-field/build.json
  src/lib/text-field/index.scss
  src/lib/text-field/index.ts
  src/lib/text-field/text-field-adapter.ts
  src/lib/text-field/text-field-component-delegate.ts
  src/lib/text-field/text-field-constants.ts
  src/lib/text-field/text-field-foundation.ts
  src/lib/text-field/text-field.html
  src/lib/text-field/text-field.scss
  src/lib/text-field/text-field.test.ts
  src/lib/text-field/text-field.ts
  src/lib/time-picker/time-picker-adapter.ts
  src/test/spec/date-picker/date-picker.spec.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
  src/test/spec/text-field/text-field.spec.ts
  src/test/spec/time-picker/time-picker.spec.ts
Labels: minor, @next

#495 feat(expansion-panel): refactor to use CSS (grid) based animation and convert to use tokens and updated patterns
  src/dev/pages/expansion-panel/expansion-panel.ejs
  src/dev/pages/expansion-panel/expansion-panel.html
  src/dev/pages/expansion-panel/expansion-panel.scss
  src/dev/pages/expansion-panel/expansion-panel.ts
  src/lib/button-area/button-area-foundation.ts
  src/lib/core/styles/tokens/expansion-panel/_tokens.scss
  src/lib/expansion-panel/_core.scss
  src/lib/expansion-panel/_mixins.scss
  src/lib/expansion-panel/_token-utils.scss
  src/lib/expansion-panel/build.json
  src/lib/expansion-panel/expansion-panel-adapter.ts
  src/lib/expansion-panel/expansion-panel-constants.ts
  src/lib/expansion-panel/expansion-panel-foundation.ts
  src/lib/expansion-panel/expansion-panel.html
  src/lib/expansion-panel/expansion-panel.scss
  src/lib/expansion-panel/expansion-panel.test.ts
  src/lib/expansion-panel/expansion-panel.ts
  src/lib/expansion-panel/forge-expansion-panel.scss
  src/lib/expansion-panel/index.scss
  src/lib/forge.scss
  src/lib/stepper/step/step-adapter.ts
  src/lib/table/table-utils.ts
  src/test/spec/accordion/accordion.spec.ts
  src/test/spec/expansion-panel/expansion-panel.spec.ts
Labels: minor, skip-release, @next

#497 fix(field): isolate stacking context
  src/lib/field-next/_core.layout.scss
  src/lib/field-next/_core.scss
  src/lib/field-next/field.scss
Labels: patch, @next

#500 feat(list-dropdown): refactored to use `<forge-popover>` instead of `<forge-popup>` internally
  src/dev/src/component-list.ts
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-constants.ts
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/autocomplete/autocomplete.ts
  src/lib/autocomplete/build.json
  src/lib/core/styles/tokens/popover/_tokens.scss
  src/lib/core/utils/feature-detection.ts
  src/lib/list-dropdown/list-dropdown-adapter.ts
  src/lib/list-dropdown/list-dropdown-constants.ts
  src/lib/list-dropdown/list-dropdown-foundation.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/list-dropdown/list-dropdown.ts
  src/lib/menu/build.json
  src/lib/menu/menu-adapter.ts
  src/lib/menu/menu-foundation.ts
  src/lib/menu/menu.ts
  src/lib/popover/_animations.scss
  src/lib/popover/_core.scss
  src/lib/popover/popover-adapter.ts
  src/lib/popover/popover-constants.ts
  src/lib/popover/popover-foundation.ts
  src/lib/popover/popover.scss
  src/lib/popover/popover.test.ts
  src/lib/popover/popover.ts
  src/lib/select/build.json
  src/lib/select/core/base-select-adapter.ts
  src/lib/select/core/base-select-foundation.ts
  src/lib/select/core/base-select.ts
  src/lib/select/select-dropdown/select-dropdown-adapter.ts
  src/lib/select/select-dropdown/select-dropdown.ts
  src/lib/select/select/select-adapter.ts
  src/lib/select/select/select.ts
  src/lib/time-picker/time-picker-adapter.ts
  src/lib/time-picker/time-picker-foundation.ts
  src/lib/time-picker/time-picker.ts
  src/test/spec/autocomplete/autocomplete.spec.ts
  src/test/spec/list-dropdown/list-dropdown-test-utils.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
  src/test/spec/menu/menu.spec.ts
  src/test/spec/select/select-dropdown.spec.ts
  src/test/spec/select/select.spec.ts
  src/test/spec/time-picker/time-picker.spec.ts
  src/test/utils/utils.ts
Labels: minor, skip-release, @next

#502 fix(field): updated "popover target" element styles to cover entire field container to fix anchor placement fallback positioning issues
  src/lib/field-next/_core.scss
Labels: patch, skip-release, @next

#503 fix(list): adjusted list and list-item styles to account for edge cases
  src/lib/core/styles/tokens/list/list-item/_tokens.scss
  src/lib/core/styles/tokens/list/list/_tokens.scss
  src/lib/core/styles/tokens/popover/_tokens.scss
  src/lib/list/list-item/_core.scss
  src/lib/list/list-item/list-item.ts
  src/lib/list/list/_core.scss
  src/lib/list/list/list.html
  src/lib/list/list/list.scss
  src/lib/list/list/list.ts
  src/lib/popover/_core.scss
Labels: patch, skip-release, @next

#501 feat(popover): automatically apply `aria-expanded` state on anchor element
  src/dev/pages/popover/popover.ts
  src/lib/popover/popover-adapter.ts
  src/lib/popover/popover-foundation.ts
  src/lib/popover/popover.test.ts
Labels: minor, skip-release, @next

#499 feat: update `forge-hyperlink` CSS class to use `text-decoration: underline`
  src/lib/button/_button.mixins.scss
Labels: minor

#505 chore(checkbox): remove input elements and bring up to date with latest patterns
  src/dev/pages/checkbox/checkbox.ejs
  src/dev/pages/checkbox/checkbox.html
  src/dev/pages/checkbox/checkbox.ts
  src/lib/checkbox/_core.scss
  src/lib/checkbox/build.json
  src/lib/checkbox/checkbox-adapter.ts
  src/lib/checkbox/checkbox-constants.ts
  src/lib/checkbox/checkbox-foundation.ts
  src/lib/checkbox/checkbox.html
  src/lib/checkbox/checkbox.scss
  src/lib/checkbox/checkbox.test.ts
  src/lib/checkbox/checkbox.ts
  src/lib/constants.ts
  src/lib/core/styles/tokens/checkbox/_tokens.scss
Labels: skip-release, @next

#506 feat(select): refactor to use `<forge-field>`
  src/dev/pages/select/select.ejs
  src/dev/pages/select/select.html
  src/dev/pages/select/select.ts
  src/dev/pages/text-field/text-field.ts
  src/lib/button-area/button-area.test.ts
  src/lib/core/styles/tokens/field/_tokens.scss
  src/lib/core/styles/tokens/select/_tokens.scss
  src/lib/field-next/_core.layout.scss
  src/lib/field-next/_core.scss
  src/lib/field-next/_core.shape.scss
  src/lib/field-next/_core.variant.scss
  src/lib/field-next/base/with-base-field.ts
  src/lib/field-next/field-adapter.ts
  src/lib/field-next/field-constants.ts
  src/lib/field-next/field-foundation.ts
  src/lib/field-next/field.html
  src/lib/field-next/field.scss
  src/lib/field-next/field.ts
  src/lib/focus-indicator/focus-indicator-constants.ts
  src/lib/focus-indicator/focus-indicator-foundation.ts
  src/lib/focus-indicator/focus-indicator.ts
  src/lib/paginator/paginator.html
  src/lib/popover/popover-adapter.ts
  src/lib/select/core/base-select-adapter.ts
  src/lib/select/core/base-select-constants.ts
  src/lib/select/index.scss
  src/lib/select/select-dropdown/select-dropdown-adapter.ts
  src/lib/select/select/_base.scss
  src/lib/select/select/_core.scss
  src/lib/select/select/_mixins.scss
  src/lib/select/select/_selector.scss
  src/lib/select/select/_token-utils.scss
  src/lib/select/select/_variables.scss
  src/lib/select/select/select-adapter.ts
  src/lib/select/select/select-constants.ts
  src/lib/select/select/select-foundation.ts
  src/lib/select/select/select.html
  src/lib/select/select/select.scss
  src/lib/select/select/select.test.ts
  src/lib/select/select/select.ts
  src/stories/src/components/select/select-args.ts
  src/stories/src/components/select/select.mdx
  src/test/spec/select/select-component-delegate.spec.ts
  src/test/spec/select/select.spec.ts
  web-test-runner.config.mjs
Labels: minor, skip-release, @next

#507 feat(icon): refactor to use tokens and improve performance
  src/dev/pages/icon/icon.ejs
  src/lib/core/styles/tokens/icon/_tokens.scss
  src/lib/core/utils/svg-utils.ts
  src/lib/icon/_core.scss
  src/lib/icon/_mixins.scss
  src/lib/icon/_token-utils.scss
  src/lib/icon/_variables.scss
  src/lib/icon/build.json
  src/lib/icon/icon-adapter.ts
  src/lib/icon/icon-constants.ts
  src/lib/icon/icon-foundation.ts
  src/lib/icon/icon-registry.ts
  src/lib/icon/icon-utils.ts
  src/lib/icon/icon.scss
  src/lib/icon/icon.test.ts
  src/lib/icon/icon.ts
  src/lib/icon/index.scss
  src/lib/icon/index.ts
  src/test/spec/icon/icon.spec.ts
Labels: minor, skip-release, @next

#508 fix(select-dropdown): fixed a bug where the space key was triggering multiple click events due to bubbling when attached to a `<forge-button>`
  src/lib/select/core/base-select-foundation.ts
Labels: patch, skip-release, @next

#509 feat(card): refactor to use tokens
  src/lib/card/_core.scss
  src/lib/card/_mixins.scss
  src/lib/card/_token-utils.scss
  src/lib/card/_variables.scss
  src/lib/card/build.json
  src/lib/card/card-constants.ts
  src/lib/card/card.scss
  src/lib/card/card.test.ts
  src/lib/card/card.ts
  src/lib/card/index.scss
  src/lib/card/index.ts
  src/lib/core/styles/tokens/card/_tokens.scss
Labels: minor, skip-release, @next

#496 feat(stepper): refactor to use tokens, focus-indicator, and state-layer
  src/lib/core/styles/tokens/stepper/step/_tokens.scss
  src/lib/stepper/step/_core.scss
  src/lib/stepper/step/_mixins.scss
  src/lib/stepper/step/_token-utils.scss
  src/lib/stepper/step/_variables.scss
  src/lib/stepper/step/step-adapter.ts
  src/lib/stepper/step/step-constants.ts
  src/lib/stepper/step/step-foundation.ts
  src/lib/stepper/step/step.html
  src/lib/stepper/step/step.scss
  src/lib/stepper/step/step.ts
  src/lib/stepper/stepper/_core.scss
  src/lib/stepper/stepper/_mixins.scss
  src/lib/stepper/stepper/stepper-constants.ts
  src/lib/stepper/stepper/stepper.scss
Labels: minor, skip-release, @next

#511 chore(switch): remove input elements and bring up to date with latest patterns
  src/dev/pages/switch/switch.ejs
  src/lib/checkbox/checkbox-constants.ts
  src/lib/checkbox/checkbox-foundation.ts
  src/lib/checkbox/checkbox.ts
  src/lib/switch/_core.scss
  src/lib/switch/build.json
  src/lib/switch/switch-adapter.ts
  src/lib/switch/switch-constants.ts
  src/lib/switch/switch-foundation.ts
  src/lib/switch/switch.html
  src/lib/switch/switch.test.ts
  src/lib/switch/switch.ts
Labels: minor, skip-release, @next
