Repository tyler-technologies-oss/forge, pull requests merged in 2024-02, with the labels that each got.

#462 [@next][inline-message] refactor to use tokens
  package-lock.json
  package.json
  src/dev/pages/inline-message/inline-message.ejs
  src/dev/pages/inline-message/inline-message.html
  src/dev/pages/inline-message/inline-message.ts
  src/dev/pages/theme/theme.ts
  src/lib/core/styles/tokens/inline-message/_tokens.scss
  src/lib/core/styles/tokens/theme/_token-utils.scss
  src/lib/inline-message/_core.scss
  src/lib/inline-message/_mixins.scss
  src/lib/inline-message/_token-utils.scss
  src/lib/inline-message/_variables.scss
  src/lib/inline-message/index.scss
  src/lib/inline-message/inline-message-constants.ts
  src/lib/inline-message/inline-message.html
  src/lib/inline-message/inline-message.scss
  src/lib/inline-message/inline-message.test.ts
  src/lib/inline-message/inline-message.ts
  src/lib/state-layer/state-layer-foundation.ts
  src/lib/theme/_theme-dark.scss
  src/test/spec/inline-message/inline-message.fixture.html
  src/test/spec/inline-message/inline-message.spec.ts
Labels: minor, skip-release, @next

#463 [@next][badge] refactor to use design tokens
  src/dev/pages/badge/badge.ejs
  src/dev/pages/badge/badge.ts
  src/lib/app-bar/notification-button/app-bar-notification-button-adapter.ts
  src/lib/app-bar/notification-button/app-bar-notification-button.test.ts
  src/lib/badge/_core.scss
  src/lib/badge/_token-utils.scss
  src/lib/badge/badge-adapter.ts
  src/lib/badge/badge-component-delegate.ts
  src/lib/badge/badge-constants.ts
  src/lib/badge/badge-foundation.ts
  src/lib/badge/badge.html
  src/lib/badge/badge.scss
  src/lib/badge/badge.test.ts
  src/lib/badge/badge.ts
  src/lib/badge/build.json
  src/lib/badge/index.scss
  src/lib/badge/index.ts
  src/lib/circular-progress/circular-progress-foundation.ts
  src/lib/core/styles/tokens/badge/_tokens.scss
  src/stories/src/components/badge/badge-arg-types.ts
  src/stories/src/components/badge/badge.stories.tsx
  src/test/spec/badge/badge.spec.ts
Labels: minor, @next

#464 feat(banner): refactor to use design tokens and updated patterns
  src/dev/pages/banner/banner.html
  src/dev/pages/banner/banner.ts
  src/lib/badge/_mixins.scss
  src/lib/badge/_variables.scss
  src/lib/badge/badge.test.ts
  src/lib/banner/_core.scss
  src/lib/banner/_mixins.scss
  src/lib/banner/_token-utils.scss
  src/lib/banner/_variables.scss
  src/lib/banner/banner-adapter.ts
  src/lib/banner/banner-constants.ts
  src/lib/banner/banner-foundation.ts
  src/lib/banner/banner.html
  src/lib/banner/banner.scss
  src/lib/banner/banner.test.ts
  src/lib/banner/banner.ts
  src/lib/banner/build.json
  src/lib/banner/index.scss
  src/lib/core/styles/tokens/banner/_tokens.scss
  src/lib/theme/_theme-dark.scss
  src/stories/src/components/banner/banner-args.ts
  src/stories/src/components/banner/banner.mdx
  src/stories/src/components/banner/banner.stories.tsx
  src/test/spec/banner/banner.fixture.html
  src/test/spec/banner/banner.spec.ts
Labels: minor, @next

#465 fix: identify readonly properties in custom elements manifest
  package-lock.json
  package.json
  src/lib/autocomplete/autocomplete.ts
  src/lib/calendar/calendar.ts
  src/lib/menu/menu.ts
  src/lib/select/core/base-select.ts
  src/lib/tooltip/tooltip.ts
Labels: patch, skip-release

#466 feat(banner): add before dismiss event and theme updates
  src/dev/pages/banner/banner.html
  src/dev/pages/banner/banner.ts
  src/lib/banner/_core.scss
  src/lib/banner/banner-adapter.ts
  src/lib/banner/banner-constants.ts
  src/lib/banner/banner-foundation.ts
  src/lib/banner/banner.html
  src/lib/banner/banner.scss
  src/lib/banner/banner.test.ts
  src/lib/banner/banner.ts
  src/lib/core/styles/tokens/banner/_tokens.scss
Labels: patch, skip-release, @next

#467 fix(overlay): update how flip positioning is handled
  src/lib/core/utils/position-utils.ts
  src/lib/core/utils/utils.ts
  src/lib/overlay/overlay-adapter.ts
  src/lib/overlay/overlay-constants.ts
  src/lib/overlay/overlay-foundation.ts
  src/lib/popover/popover.test.ts
  src/lib/typings.d.ts
Labels: patch, @next

#470 feat(divider): refactor to use tokens
  src/lib/button/button.scss
  src/lib/core/styles/tokens/divider/_tokens.scss
  src/lib/divider/_core.scss
  src/lib/divider/_mixins.scss
  src/lib/divider/_token-utils.scss
  src/lib/divider/_variables.scss
  src/lib/divider/build.json
  src/lib/divider/divider-constants.ts
  src/lib/divider/divider.html
  src/lib/divider/divider.scss
  src/lib/divider/divider.test.ts
  src/lib/divider/divider.ts
  src/lib/divider/index.scss
  src/lib/drawer/drawer/drawer.scss
  src/lib/drawer/mini-drawer/mini-drawer.scss
  src/lib/drawer/modal-drawer/modal-drawer.scss
  src/test/spec/divider/divider.spec.ts
Labels: minor, skip-release, @next

#456 [@next] create low level field component
  src/dev/pages/field/field.ejs
  src/dev/pages/field/field.html
  src/dev/pages/field/field.scss
  src/dev/pages/field/field.ts
  src/dev/pages/theme/theme.ts
  src/dev/pages/typography/typography.ejs
  src/dev/src/components.json
  src/lib/badge/_core.scss
  src/lib/checkbox/_core.scss
  src/lib/constants.ts
  src/lib/core/styles/tokens/_token-utils.scss
  src/lib/core/styles/tokens/field/_tokens.scss
  src/lib/core/styles/tokens/typography/_scale.scss
  src/lib/core/styles/tokens/typography/_tokens.label.scss
  src/lib/core/utils/utils.ts
  src/lib/field-next/_core.layout.scss
  src/lib/field-next/_core.scss
  src/lib/field-next/_core.shape.scss
  src/lib/field-next/_core.slotted.scss
  src/lib/field-next/_core.state.scss
  src/lib/field-next/_core.variant.scss
  src/lib/field-next/_token-utils.scss
  src/lib/field-next/field-adapter.ts
  src/lib/field-next/field-constants.ts
  src/lib/field-next/field-foundation.ts
  src/lib/field-next/field.html
  src/lib/field-next/field.scss
  src/lib/field-next/field.test.ts
  src/lib/field-next/field.ts
  src/lib/field-next/index.scss
  src/lib/field-next/index.ts
  src/lib/index.ts
  src/lib/label/_core.scss
  src/lib/label/label-constants.ts
  src/lib/label/label-foundation.ts
  src/lib/label/label.ts
  src/lib/radio/build.json
  src/lib/radio/radio-group/_core.scss
  src/lib/radio/radio-group/index.scss
  src/lib/radio/radio-group/radio-group-adapter.ts
  src/lib/radio/radio-group/radio-group-component-delegate.ts
  src/lib/radio/radio-group/radio-group.scss
  src/lib/radio/radio/_core.scss
  src/lib/radio/radio/build.json
  src/lib/radio/radio/radio.ts
  src/lib/slider/_core.scss
  src/lib/switch/_core.scss
Labels: minor, skip-release, @next

#473 fix(tooltip): ensure `white-space` style is not inherited from ancestors to avoid overflow with wrapping text
  src/lib/tooltip/_core.scss
Labels: patch, skip-release, @next

#449 fix(open-icon): auto-register correct "horizontal" icon
  src/lib/open-icon/open-icon.ts
Labels: patch, skip-release

#457 fix(dialog): fixed a bug where opening dialogs with focused Forge elements that use the ripple could be misaligned
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-foundation.ts
Labels: patch, skip-release

#458 fix(list): fixed a bug where keyboard navigation was not scoped within sub-lists
  src/lib/core/base/base-adapter.ts
  src/lib/list/list/list-adapter.ts
  src/lib/list/list/list-constants.ts
  src/lib/list/list/list-foundation.ts
Labels: patch, skip-release

#459 fix(list): fixed keyboard navigation and used `gap` instead of `margin` for leading/trailing slots
  src/dev/pages/list/list.ejs
  src/lib/core/styles/tokens/list/list-item/_tokens.scss
  src/lib/list/list-item/_core.scss
  src/lib/list/list-item/list-item-constants.ts
  src/lib/list/list-item/list-item.scss
  src/lib/list/list-item/list-item.ts
  src/lib/list/list/list-adapter.ts
  src/lib/list/list/list-constants.ts
  src/lib/list/list/list-foundation.ts
  src/lib/popover/popover.test.ts
Labels: patch, skip-release

#468 fix(paginator): revert naive focus management changes in favor of default browser implementation when focused elements are disabled
  src/lib/button-area/button-area-adapter.ts
  src/lib/button-area/button-area-foundation.ts
  src/lib/button/button.ts
  src/lib/checkbox/checkbox-adapter.ts
  src/lib/core/utils/utils.ts
  src/lib/icon-button/icon-button.ts
  src/lib/list/list-item/list-item-adapter.ts
  src/lib/list/list-item/list-item-foundation.ts
  src/lib/paginator/paginator-adapter.ts
  src/lib/paginator/paginator-constants.ts
  src/lib/paginator/paginator-foundation.ts
  src/lib/radio/radio-adapter.ts
  src/lib/ripple/forge-ripple.ts
  src/lib/switch/switch.ts
  src/test/spec/paginator/paginator.spec.ts
Labels: patch, skip-release

#461 fix(menu): map deprecated `icon` property to `leadingIcon` when options are loaded from factory
  src/lib/menu/menu-foundation.ts
  src/test/spec/menu/menu.spec.ts
Labels: patch, skip-release

#472 fix(date-picker): open calendar on min enabled month when current month is after max date
  src/lib/calendar/calendar-foundation.ts
  src/lib/date-picker/base/base-date-picker-adapter.ts
  src/lib/date-picker/base/base-date-picker-foundation.ts
  src/test/spec/date-picker/date-picker.spec.ts
Labels: patch

#475 feat: bump `@tylertech/forge-core` to `2.3.1` to use constructable stylesheets by default
  package-lock.json
  package.json
Labels: patch

#479 chore: upgrade auto to fix release
  package-lock.json
  package.json
Labels: patch

#482 Next stack refactor
  src/dev/pages/stack/stack.ejs
  src/dev/pages/stack/stack.html
  src/dev/pages/stack/stack.scss
  src/dev/pages/stack/stack.ts
  src/lib/core/styles/tokens/stack/_tokens.scss
  src/lib/stack/_core.scss
  src/lib/stack/_mixins.scss
  src/lib/stack/_token-utils.scss
  src/lib/stack/_variables.scss
  src/lib/stack/stack-constants.ts
  src/lib/stack/stack-foundation.ts
  src/lib/stack/stack.scss
  src/lib/stack/stack.test.ts
  src/lib/stack/stack.ts
  src/test/spec/stack/stack.spec.ts
Labels: minor, skip-release, @next

#481 feat(skeleton): tokenize forge skeleton
  src/lib/core/styles/tokens/skeleton/_tokens.scss
  src/lib/skeleton/_animations.scss
  src/lib/skeleton/_core.scss
  src/lib/skeleton/_mixins.scss
  src/lib/skeleton/_token-utils.scss
  src/lib/skeleton/_variables.scss
  src/lib/skeleton/build.json
  src/lib/skeleton/index.scss
  src/lib/skeleton/skeleton.html
  src/lib/skeleton/skeleton.scss
  src/lib/skeleton/skeleton.ts
  src/lib/theme/_theme-dark.scss
Labels: minor, skip-release, @next

#483 feat(chips): refactor to use tokens
  src/dev/pages/chips/chips.ejs
  src/dev/pages/chips/chips.html
  src/dev/pages/chips/chips.ts
  src/lib/avatar/index.scss
  src/lib/chip-field/chip-field-foundation.ts
  src/lib/chips/build.json
  src/lib/chips/chip-set/_core.scss
  src/lib/chips/chip-set/_mixins.scss
  src/lib/chips/chip-set/_token-utils.scss
  src/lib/chips/chip-set/_variables.scss
  src/lib/chips/chip-set/chip-set-adapter.ts
  src/lib/chips/chip-set/chip-set-constants.ts
  src/lib/chips/chip-set/chip-set-foundation.ts
  src/lib/chips/chip-set/chip-set.scss
  src/lib/chips/chip-set/chip-set.ts
  src/lib/chips/chip-set/index.scss
  src/lib/chips/chip-set/index.ts
  src/lib/chips/chip/_core.scss
  src/lib/chips/chip/_mixins.scss
  src/lib/chips/chip/_token-utils.scss
  src/lib/chips/chip/_variables.scss
  src/lib/chips/chip/chip-adapter.ts
  src/lib/chips/chip/chip-checkmark.html
  src/lib/chips/chip/chip-constants.ts
  src/lib/chips/chip/chip-foundation.ts
  src/lib/chips/chip/chip.html
  src/lib/chips/chip/chip.scss
  src/lib/chips/chip/chip.ts
  src/lib/chips/chip/index.scss
  src/lib/chips/chips.test.ts
  src/lib/core/styles/tokens/chips/chip-set/_tokens.scss
  src/lib/core/styles/tokens/chips/chip/_tokens.scss
  src/lib/theme/_theme-dark.scss
  src/stories/src/components/chip-field/chip-field.stories.tsx
  src/test/spec/chip-field/chip-field.spec.ts
  src/test/spec/chips/chips.spec.ts
Labels: minor, skip-release, @next

#484 feat(toolbar): refactor to use tokens
  src/dev/pages/toolbar/toolbar.ejs
  src/dev/pages/toolbar/toolbar.scss
  src/dev/src/shared.ts
  src/lib/core/styles/tokens/toolbar/_tokens.scss
  src/lib/profile-card/profile-card.scss
  src/lib/toolbar/_core.scss
  src/lib/toolbar/_mixins.scss
  src/lib/toolbar/_token-utils.scss
  src/lib/toolbar/_variables.scss
  src/lib/toolbar/build.json
  src/lib/toolbar/index.scss
  src/lib/toolbar/toolbar-constants.ts
  src/lib/toolbar/toolbar.html
  src/lib/toolbar/toolbar.scss
  src/lib/toolbar/toolbar.test.ts
  src/lib/toolbar/toolbar.ts
  src/test/spec/toolbar/toolbar.spec.ts
Labels: minor, skip-release, @next

#487 feat(popover): new delay property
  src/dev/pages/popover/popover.html
  src/dev/pages/popover/popover.ts
  src/lib/popover/popover-constants.ts
  src/lib/popover/popover-foundation.ts
  src/lib/popover/popover.test.ts
  src/lib/popover/popover.ts
Labels: enhancement, minor, skip-release, @next

#488 feat(product-icon): remove product icon component
  src/lib/index.ts
  src/lib/product-icon/_mixins.scss
  src/lib/product-icon/_variables.scss
  src/lib/product-icon/build.json
  src/lib/product-icon/index.ts
  src/lib/product-icon/product-icon-adapter.ts
  src/lib/product-icon/product-icon-constants.ts
  src/lib/product-icon/product-icon-foundation.ts
  src/lib/product-icon/product-icon.html
  src/lib/product-icon/product-icon.scss
  src/lib/product-icon/product-icon.ts
  src/stories/src/components/product-icon/code/product-icon-custom-color.ts
  src/stories/src/components/product-icon/code/product-icon-custom-shadow.ts
  src/stories/src/components/product-icon/code/product-icon-custom-size.ts
  src/stories/src/components/product-icon/code/product-icon-default.ts
  src/stories/src/components/product-icon/code/product-icon-text.ts
  src/stories/src/components/product-icon/product-icon-args.ts
  src/stories/src/components/product-icon/product-icon.mdx
  src/stories/src/components/product-icon/product-icon.stories.tsx
  src/test/spec/product-icon/product-icon.spec.ts
Labels: minor, skip-release, @next
