Repository tyler-technologies-oss/forge, pull requests merged in 2024-07, with the labels that each got.

#637 fix(app-bar-notification-button): fixed a bug where the count could incorrectly display when in dot mode if not changed from default
  src/lib/app-bar/notification-button/app-bar-notification-button-foundation.ts
Labels: patch, skip-release, @2.x

#643 [field] fix initialization of internal element references to occur in constructor instead of connectedCallback
  src/lib/chip-field/chip-field-adapter.ts
  src/lib/field/field-adapter.ts
  src/lib/field/field-foundation.ts
  src/lib/text-field/text-field-adapter.ts
Labels: patch, @2.x

#645 fix(button): fix to properly wire up raised variant-specific tokens
  src/lib/button/_core.scss
  src/lib/button/button.scss
  src/lib/button/button.ts
  src/lib/core/styles/tokens/button/_tokens.scss
Labels: patch, skip-release

#644 fix(icon-button): fix to properly default `theme` to "default" to allow for "primary" to be used like other themes
  src/dev/pages/icon-button/icon-button.html
  src/lib/icon-button/icon-button-constants.ts
  src/lib/icon-button/icon-button.test.ts
  src/lib/icon-button/icon-button.ts
  src/stories/components/button/Button.stories.ts
  src/stories/components/icon-button/IconButton.stories.ts
Labels: patch, skip-release

#639 fix(app-bar-notification-button): fixed a bug where the count could incorrectly display when in dot mode if not changed from default
  src/lib/app-bar/notification-button/app-bar-notification-button-core.ts
Labels: patch, skip-release

#638 fix(list-item): separate the foreground and background selected state tokens
  src/lib/core/styles/tokens/list/list-item/_tokens.scss
  src/lib/list/list-item/_core.scss
  src/lib/list/list-item/list-item.ts
Labels: patch, skip-release

#646 docs: add temporary banner with link to v2.x docs
  .storybook/manager-head.html
  .storybook/manager.ts
Labels: documentation, skip-release

#649 fix(select): temp fix to remove disabled property from form associated mixin for TS2611 until TypeScript fixes accessor union bug
  src/dev/pages/table/table.ts
  src/lib/core/mixins/form/with-form-associated.ts
  src/lib/select/select/select.ts
Labels: patch, skip-release

#652 refactor: add unique identifier to table data items
  src/stories/components/table/Table.stories.ts
Labels: documentation, skip-release

#650 docs: fix event types
  src/lib/app-bar/profile-button/app-bar-profile-button.ts
  src/lib/autocomplete/autocomplete.ts
  src/lib/banner/banner.ts
  src/lib/chips/chip/chip.ts
  src/lib/icon-button/icon-button.ts
  src/lib/split-view/split-view-panel/split-view-panel.ts
Labels: documentation, skip-release

#655 chore: fix compatibility with windows systems to use normalized file paths in CLI and build-tools deps as well as line endings in eslint
  .eslintrc.json
  package-lock.json
  package.json
Labels: skip-release

#656 fix(theme): use correct error theme color in dark theme
  src/lib/badge/badge.scss
  src/lib/core/styles/tokens/theme/_tokens.status.scss
Labels: patch, skip-release

#657 feat(tokens): include color-emphasis tokens as part of the `forge-tokens.css` stylesheet
  src/lib/core/styles/theme/_color-utils.scss
  src/lib/core/styles/theme/index.scss
  src/lib/core/styles/tokens/theme/_token-utils.scss
  src/lib/forge-tokens.scss
Labels: minor, skip-release

#658 feat(dialog): automatically switch to fullscreen at the new `fullscreenThreshold` property value
  src/dev/pages/dialog/dialog.ts
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-constants.ts
  src/lib/dialog/dialog-core.ts
  src/lib/dialog/dialog.test.ts
  src/lib/dialog/dialog.ts
  src/stories/components/dialog/Dialog.mdx
  src/stories/components/dialog/Dialog.stories.ts
  src/stories/components/dialog/Dialog.ts
  web-test-runner.config.mjs
Labels: minor, skip-release

#654 docs(select): update incorrect slot docs
  src/lib/select/select/select.ts
Labels: documentation, skip-release

#660 fix(tab): add missing inline padding
  src/lib/core/styles/tokens/tabs/tab/_tokens.scss
  src/lib/tabs/tab/_core.scss
  src/lib/tabs/tab/tab.scss
  src/lib/tabs/tab/tab.ts
Labels: patch, skip-release, storybook-preview
