Repository tyler-technologies-oss/forge, pull requests merged in 2024-09, with the labels that each got.

#675 feat(shape): enable use of `--forge-shape-factor` to uniformly control shape tokens via multiplier
  src/lib/core/styles/shape/index.scss
Labels: minor, skip-release

#680 fix(autocomplete): focus `<input>` popover icon is clicked if composed with a `<forge-text-field popover-icon>`
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/field/field-core.ts
Labels: patch, skip-release

#681 feat: bump to latest Forge CLI
  package-lock.json
  package.json
  src/stories/components/app-bar/AppBar.mdx
  src/stories/components/app-bar/profile/profile.stories.ts
  src/stories/components/badge/Badge.mdx
  src/stories/design-tokens/Shape.mdx
  src/stories/getting-started/Installation.mdx
Labels: documentation, minor

#687 feat: handle non-string values in checkbox, switch, and radio
  src/lib/checkbox/checkbox-core.ts
  src/lib/checkbox/checkbox.test.ts
  src/lib/radio/radio/radio-core.ts
  src/lib/radio/radio/radio.test.ts
  src/lib/switch/switch-core.ts
  src/lib/switch/switch.test.ts
Labels: patch

#693 docs: removed DialogConfig
  src/stories/components/dialog/Dialog.mdx
Labels: documentation, skip-release

#690 fix(list-dropdown): restore display of secondaryLabel
  src/dev/pages/autocomplete/autocomplete.html
  src/dev/pages/autocomplete/autocomplete.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
Labels: patch, skip-release

#691 fix(stepper): remove the internal `z-index` style and fix overflowing content
  src/lib/stepper/step/_core.scss
Labels: patch, skip-release

#692 fix(list-item): use `layout` containment on the text-container part to ensure that slotted elements (specifically tooltips) do no affect the layout
  src/lib/list/list-item/_core.scss
Labels: patch, skip-release

#688 fix(date-picker): ensure that time portion of `Date` value is preserved during initial render and dropdown calendar selection
  src/lib/core/utils/date-utils.ts
  src/lib/date-picker/date-picker-core.ts
  src/lib/date-range-picker/date-range-picker-core.ts
  src/test/spec/date-picker/date-picker.spec.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
Labels: patch

#694 fix(date-picker): ensure that time portion of `Date` value is preserved during initial render and dropdown calendar selection
  src/lib/core/utils/date-utils.ts
  src/lib/date-picker/date-picker-foundation.ts
  src/lib/date-range-picker/date-range-picker-foundation.ts
  src/test/spec/date-picker/date-picker.spec.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
Labels: patch

#697 fix(date-range-picker): fixed a bug where multiple input separators could be added
  src/lib/date-range-picker/date-range-picker-adapter.ts
Labels: patch, skip-release

#698 fix(list-item): fixed a bug where focus was being forced to propagate to the interactive element when used within a list dropdown
  src/dev/pages/list/list.scss
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/list/list-item/list-item-constants.ts
  src/lib/list/list-item/list-item-core.ts
  src/lib/list/list-item/list-item.ts
Labels: patch

#696 fix(text-field): fixed a bug where multiple input separators could be added
  src/lib/text-field/text-field-adapter.ts
Labels: patch
