Repository tyler-technologies-oss/forge, pull requests merged in 2024-12, with the labels that each got.

#767 [icon-button] improve docs for toggle mode + background color for "icon" variant when toggled on
  src/lib/calendar/calendar-core.ts
  src/lib/core/styles/tokens/icon-button/_tokens.scss
  src/lib/icon-button/_core.scss
  src/lib/icon-button/icon-button.ts
  src/stories/components/icon-button/IconButton.mdx
  src/stories/components/icon-button/IconButton.stories.ts
  src/test/spec/date-picker/date-picker.spec.ts
Labels: documentation, enhancement, minor, skip-release

#765 fix(popover): delay visibility check when hiding by a frame to ensure style calculation has enough time to execute
  src/lib/popover/popover-adapter.ts
Labels: patch, skip-release

#771 feat(toolbar): make columns customizable
  src/lib/core/styles/tokens/toolbar/_tokens.scss
  src/lib/toolbar/_core.scss
  src/lib/toolbar/toolbar.ts
Labels: enhancement, minor, skip-release

#770 feat(typography): add new `label3` style
  src/dev/pages/typography/typography.ejs
  src/lib/core/styles/tokens/typography/_tokens.label.scss
  src/stories/design-tokens/Typography.mdx
  src/stories/getting-started/Typography.mdx
Labels: enhancement, minor, skip-release

#766 feat(tabs): deprecate `secondary` prop/attr and update default design to use full width tab indicator
  src/dev/pages/tabs/tabs.ejs
  src/dev/pages/tabs/tabs.html
  src/dev/pages/tabs/tabs.ts
  src/lib/core/styles/tokens/tabs/tab/_tokens.scss
  src/lib/tabs/tab-bar/_core.scss
  src/lib/tabs/tab-bar/tab-bar-core.ts
  src/lib/tabs/tab-bar/tab-bar.ts
  src/lib/tabs/tab/_core.scss
  src/lib/tabs/tab/tab-adapter.ts
  src/lib/tabs/tab/tab-core.ts
  src/lib/tabs/tab/tab.scss
  src/lib/tabs/tab/tab.ts
  src/lib/tabs/tabs.test.ts
  src/stories/components/tabs/Tabs.mdx
  src/stories/components/tabs/Tabs.stories.ts
Labels: minor, skip-release, storybook-preview

#769 fix: update checkbox, radio, switch label typography to use `label2` (13px) typography by default
  src/dev/pages/checkbox/checkbox.ejs
  src/dev/pages/radio/radio.ejs
  src/dev/pages/switch/switch.ejs
  src/lib/checkbox/_core.scss
  src/lib/radio/radio/_core.scss
  src/lib/switch/_core.scss
  src/stories/components/checkbox/Checkbox.stories.ts
  src/stories/components/radio/Radio.stories.ts
  src/stories/components/switch/Switch.stories.ts
Labels: patch, storybook-preview
