Repository tyler-technologies-oss/forge, pull requests merged in 2024-10, with the labels that each got.

#700 fix(chip): remove attribute syncing to prevent value being forced to string
  src/lib/chips/chip/chip-core.ts
  src/lib/chips/chips.test.ts
Labels: patch, skip-release

#701 feat(calendar): enable UI text customization
  src/lib/calendar/calendar-adapter.ts
  src/lib/calendar/calendar-constants.ts
  src/lib/calendar/calendar-core.ts
  src/lib/calendar/calendar-dom-utils.ts
  src/lib/calendar/calendar-dropdown/calendar-dropdown-constants.ts
  src/lib/calendar/calendar.ts
  src/lib/date-picker/base/base-date-picker-adapter.ts
  src/lib/date-picker/base/base-date-picker-constants.ts
  src/lib/date-picker/base/base-date-picker-core.ts
  src/lib/date-picker/base/base-date-picker.ts
  src/test/spec/date-picker/date-picker.spec.ts
Labels: enhancement, minor

#705 fix(chip-field): add `focus-indicator-color` token to chips to fix themed "field" chips
  src/lib/chip-field/chip-field.scss
  src/lib/chips/chip/chip.scss
  src/lib/chips/chip/chip.ts
  src/lib/core/styles/tokens/chips/chip/_tokens.scss
Labels: patch, skip-release

#708 fix(inline-message): fix content alignment
  src/lib/inline-message/_core.scss
Labels: patch, skip-release

#711 fix(circular-progress): updated the host element to set `block-size` and `inline-size` explicitly
  src/lib/circular-progress/_core.scss
Labels: patch, skip-release

#719 docs(page-state): apply CSS var controls to default demo story
  src/stories/components/page-state/PageState.stories.ts
Labels: documentation, skip-release

#718 fix(paginator): append select popover to shadow root to attach IDREFs
  src/dev/pages/paginator/paginator.ejs
  src/lib/paginator/paginator.html
Labels: patch, skip-release

#714 docs(app-bar): add missing description for `target` property & attribute
  src/lib/app-bar/app-bar/app-bar.ts
Labels: documentation, skip-release

#713 fix(base-button): fixed a bug where calling `.click()` on a button before it's connected would result in an exception
  src/lib/button/base/base-button-adapter.ts
Labels: patch, skip-release

#704 fix(skip-link): allow focusing without url navigation
  src/dev/pages/skip-link/skip-link.html
  src/dev/pages/skip-link/skip-link.ts
  src/lib/skip-link/skip-link-constants.ts
  src/lib/skip-link/skip-link.test.ts
  src/lib/skip-link/skip-link.ts
  src/stories/components/skip-link/SkipLink.stories.ts
Labels: enhancement, minor, skip-release, accessibility

#706 fix(autocomplete): properly reflect dropdown open state if dismissed by anchor click
  src/lib/autocomplete/autocomplete-adapter.ts
  src/test/spec/autocomplete/autocomplete.spec.ts
Labels: patch, skip-release

#703 fix(field): extend box to include outline
  src/lib/field/_core.scss
  src/lib/field/field.scss
  src/lib/field/forge-field.scss
Labels: patch, skip-release

#710 fix(field): fixed a rare bug where the inset label state was not initializing properly based on the existence of slotted content
  src/lib/field/field-adapter.ts
  src/lib/field/field-core.ts
  src/lib/select/select/select.html
  src/lib/text-field/text-field-adapter.ts
  src/lib/text-field/text-field-constants.ts
  src/lib/text-field/text-field-core.ts
Labels: patch, skip-release

#717 fix(tab-bar): allow individually disabled tabs with enabled tab-bar
  src/lib/tabs/tab-bar/tab-bar-core.ts
  src/lib/tabs/tab-bar/tab-bar.ts
  src/lib/tabs/tab/tab-constants.ts
  src/lib/tabs/tab/tab.ts
  src/lib/tabs/tabs.test.ts
Labels: patch

#727 fix(button): fixed inline padding on all non-text variants
  src/dev/pages/button/button.ejs
  src/dev/pages/button/button.scss
  src/dev/src/styles/_flex.scss
  src/lib/button/_core.scss
  src/lib/button/button.scss
  src/lib/button/button.ts
  src/lib/button/forge-button.scss
  src/lib/core/styles/tokens/button/_tokens.scss
Labels: patch, skip-release

#721 fix(dialog): expose CSS-only stylesheet
  src/lib/dialog/_animations.scss
  src/lib/dialog/build.json
  src/lib/dialog/dialog.scss
Labels: patch, skip-release

#725 fix: fixed a composition/initialization bug for `<forge-autocomplete>` and `<forge-app-bar-search>`
  src/lib/app-bar/search/app-bar-search-adapter.ts
  src/lib/app-bar/search/app-bar-search.html
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-core.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/popover/popover-core.ts
Labels: patch, skip-release

#720 fix(field): use error color for support text when field is invalid
  src/lib/field/_core.theme.scss
  src/lib/field/field.scss
Labels: patch
