Repository tyler-technologies-oss/forge, pull requests merged in 2024-04, with the labels that each got.

#512 feat(forge-core): update core styles
  src/lib/forge-core.scss
  src/lib/utils/_mixins-core.scss
Labels: minor, skip-release, @next

#516 fix(list-item): fixed a bug where clicking list items would uncheck slotted radio buttons
  src/lib/list/list-item/list-item-adapter.ts
  src/test/spec/list/list-item/list-item.spec.ts
Labels: patch

#517 feat(label-value): refactor to use tokens
  src/dev/pages/label-value/label-value.ejs
  src/dev/pages/label-value/label-value.scss
  src/dev/pages/label-value/label-value.ts
  src/lib/core/styles/tokens/label-value/_tokens.scss
  src/lib/field-next/field.scss
  src/lib/label-value/_core.scss
  src/lib/label-value/_mixins.scss
  src/lib/label-value/_token-utils.scss
  src/lib/label-value/_variables.scss
  src/lib/label-value/build.json
  src/lib/label-value/index.scss
  src/lib/label-value/index.ts
  src/lib/label-value/label-value-adapter.ts
  src/lib/label-value/label-value-constants.ts
  src/lib/label-value/label-value-foundation.ts
  src/lib/label-value/label-value.html
  src/lib/label-value/label-value.scss
  src/lib/label-value/label-value.test.ts
  src/lib/label-value/label-value.ts
  src/test/spec/label-value/label-value.spec.ts
Labels: minor, skip-release, @next

#518 feat(chip-field): refactor to use `<forge-field>`
  src/dev/pages/chip-field/chip-field.ejs
  src/dev/pages/chip-field/chip-field.html
  src/dev/pages/chip-field/chip-field.ts
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-constants.ts
  src/lib/chip-field/_base.scss
  src/lib/chip-field/_core.scss
  src/lib/chip-field/_mixins.scss
  src/lib/chip-field/_selector.scss
  src/lib/chip-field/_token-utils.scss
  src/lib/chip-field/_variables.scss
  src/lib/chip-field/build.json
  src/lib/chip-field/chip-field-adapter.ts
  src/lib/chip-field/chip-field-component-delegate.ts
  src/lib/chip-field/chip-field-constants.ts
  src/lib/chip-field/chip-field-foundation.ts
  src/lib/chip-field/chip-field.html
  src/lib/chip-field/chip-field.scss
  src/lib/chip-field/chip-field.test.ts
  src/lib/chip-field/chip-field.ts
  src/lib/chip-field/index.scss
  src/lib/chips/chip/_core.scss
  src/lib/core/styles/tokens/chip-field/_tokens.scss
  src/lib/core/styles/tokens/field/_tokens.scss
  src/lib/field-next/_core.layout.scss
  src/lib/field-next/base/base-field-foundation.ts
  src/lib/field-next/field.scss
  src/lib/overlay/overlay-adapter.ts
  src/lib/text-field/text-field-adapter.ts
  src/lib/text-field/text-field.ts
  src/test/spec/chip-field/chip-field-no-label.fixture.html
  src/test/spec/chip-field/chip-field-unslotted.fixture.html
  src/test/spec/chip-field/chip-field.fixture.html
  src/test/spec/chip-field/chip-field.spec.ts
Labels: minor, skip-release, @next

#522 test(radio): add tests
  src/dev/pages/radio/radio.ejs
  src/lib/checkbox/checkbox-constants.ts
  src/lib/checkbox/checkbox.test.ts
  src/lib/checkbox/checkbox.ts
  src/lib/radio/core/radio-group-manager.ts
  src/lib/radio/radio-group/radio-group-component-delegate.ts
  src/lib/radio/radio-group/radio-group-constants.ts
  src/lib/radio/radio-group/radio-group.test.ts
  src/lib/radio/radio-group/radio-group.ts
  src/lib/radio/radio/build.json
  src/lib/radio/radio/radio-adapter.ts
  src/lib/radio/radio/radio-component-delegate.ts
  src/lib/radio/radio/radio-constants.ts
  src/lib/radio/radio/radio-foundation.ts
  src/lib/radio/radio/radio.html
  src/lib/radio/radio/radio.test.ts
  src/lib/radio/radio/radio.ts
  src/lib/switch/switch-component-delegate.ts
  src/lib/switch/switch-constants.ts
  src/lib/switch/switch.test.ts
  src/lib/switch/switch.ts
Labels: skip-release, tests, @next

#519 feat(app-bar-profile-button): refactor to use `<forge-popover>`
  src/lib/app-bar/profile-button/app-bar-profile-button-adapter.ts
  src/lib/app-bar/profile-button/app-bar-profile-button-foundation.ts
  src/lib/app-bar/profile-button/app-bar-profile-button.html
  src/lib/app-bar/profile-button/app-bar-profile-button.test.ts
  src/lib/app-bar/profile-button/app-bar-profile-button.ts
  src/lib/button/base/base-button-foundation.ts
  src/lib/core/base/base-adapter.ts
Labels: minor, skip-release, @next

#523 fix(dialog): use `visible` state attribute instead of `open` to control animations
  src/dev/pages/dialog/dialog.scss
  src/lib/dialog/_core.scss
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-constants.ts
  src/lib/dialog/dialog-foundation.ts
  src/lib/dialog/dialog.scss
  src/lib/dialog/dialog.test.ts
Labels: patch, skip-release, @next

#526 feat: refactor `<forge-date-picker>` and `<forge-date-range-picker>` to use `<forge-popover>` and remove `<forge-popup>` from the library
  src/dev/pages/popup/popup.ejs
  src/dev/pages/popup/popup.html
  src/dev/pages/popup/popup.ts
  src/dev/src/components.json
  src/lib/app-bar/profile-button/app-bar-profile-button.test.ts
  src/lib/app-bar/profile-button/app-bar-profile-button.ts
  src/lib/calendar/calendar-constants.ts
  src/lib/calendar/calendar-dropdown/calendar-dropdown.ts
  src/lib/calendar/calendar-menu/calendar-menu-constants.ts
  src/lib/calendar/calendar-menu/calendar-menu.scss
  src/lib/calendar/calendar-menu/calendar-menu.ts
  src/lib/calendar/calendar.scss
  src/lib/calendar/calendar.ts
  src/lib/date-picker/date-picker.ts
  src/lib/date-range-picker/date-range-picker.ts
  src/lib/forge.scss
  src/lib/icon-button/icon-button-component-delegate.ts
  src/lib/index.ts
  src/lib/popover/popover-adapter.ts
  src/lib/popup/_mixins.scss
  src/lib/popup/_variables.scss
  src/lib/popup/build.json
  src/lib/popup/forge-popup.scss
  src/lib/popup/index.ts
  src/lib/popup/popup-adapter.ts
  src/lib/popup/popup-constants.ts
  src/lib/popup/popup-foundation.ts
  src/lib/popup/popup.html
  src/lib/popup/popup.scss
  src/lib/popup/popup.ts
  src/lib/toast/toast-constants.ts
  src/stories/src/components/menu/menu-args.tsx
  src/stories/src/components/menu/menu.mdx
  src/stories/src/components/popup/code/popup-default.module.scss
  src/stories/src/components/popup/code/popup-default.ts
  src/stories/src/components/popup/popup-arg.ts
  src/stories/src/components/popup/popup.mdx
  src/stories/src/components/popup/popup.stories.tsx
  src/stories/src/components/select/select.mdx
  src/stories/src/components/toast/toast.mdx
  src/stories/src/components/tooltip/tooltip.mdx
  src/test/spec/autocomplete/autocomplete.spec.ts
  src/test/spec/date-picker/calendar-dropdown.spec.ts
  src/test/spec/date-picker/date-picker.spec.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
  src/test/spec/popup/popup.spec.ts
  src/test/spec/select/select-dropdown.spec.ts
  src/test/utils/utils.ts
Labels: minor, skip-release, @next

#527 feat(scaffold): refactor to use tokens and grid areas
  src/dev/pages/scaffold/scaffold.ejs
  src/lib/core/styles/tokens/scaffold/_tokens.scss
  src/lib/scaffold/_core.scss
  src/lib/scaffold/_mixins.scss
  src/lib/scaffold/_token-utils.scss
  src/lib/scaffold/build.json
  src/lib/scaffold/forge-scaffold.scss
  src/lib/scaffold/index.scss
  src/lib/scaffold/index.ts
  src/lib/scaffold/scaffold-constants.ts
  src/lib/scaffold/scaffold.html
  src/lib/scaffold/scaffold.scss
  src/lib/scaffold/scaffold.test.ts
  src/lib/scaffold/scaffold.ts
  src/test/spec/scaffold/scaffold.spec.ts
Labels: minor, @next

#529 fix(checkbox, radio, switch): set `justify` token to `start` by default
  src/lib/core/styles/tokens/checkbox/_tokens.scss
  src/lib/core/styles/tokens/radio/_tokens.scss
  src/lib/core/styles/tokens/switch/_tokens.scss
Labels: patch, @next

#530 feat: remove `<forge-busy-indicator>` and `<forge-quantity-field>` elements; they will be migrated to the forge extended project
  src/dev/pages/busy-indicator/busy-indicator.ejs
  src/dev/pages/busy-indicator/busy-indicator.html
  src/dev/pages/busy-indicator/busy-indicator.scss
  src/dev/pages/busy-indicator/busy-indicator.ts
  src/dev/pages/quantity-field/quantity-field.ejs
  src/dev/pages/quantity-field/quantity-field.html
  src/dev/pages/quantity-field/quantity-field.ts
  src/dev/src/components.json
  src/lib/busy-indicator/_mixins.scss
  src/lib/busy-indicator/_variables.scss
  src/lib/busy-indicator/build.json
  src/lib/busy-indicator/busy-indicator-adapter.ts
  src/lib/busy-indicator/busy-indicator-constants.ts
  src/lib/busy-indicator/busy-indicator-foundation.ts
  src/lib/busy-indicator/busy-indicator.html
  src/lib/busy-indicator/busy-indicator.scss
  src/lib/busy-indicator/busy-indicator.ts
  src/lib/busy-indicator/forge-busy-indicator.scss
  src/lib/busy-indicator/index.ts
  src/lib/forge.scss
  src/lib/index.ts
  src/lib/quantity-field/_mixins.scss
  src/lib/quantity-field/build.json
  src/lib/quantity-field/forge-quantity-field.scss
  src/lib/quantity-field/index.ts
  src/lib/quantity-field/quantity-field-adapter.ts
  src/lib/quantity-field/quantity-field-component-delegate.ts
  src/lib/quantity-field/quantity-field-constants.ts
  src/lib/quantity-field/quantity-field-foundation.ts
  src/lib/quantity-field/quantity-field.html
  src/lib/quantity-field/quantity-field.scss
  src/lib/quantity-field/quantity-field.ts
  src/stories/src/components/busy-indicator/busy-indicator-args.ts
  src/stories/src/components/busy-indicator/busy-indicator.mdx
  src/stories/src/components/busy-indicator/busy-indicator.stories.tsx
  src/stories/src/components/busy-indicator/code/busy-indicator-default.ts
  src/stories/src/components/busy-indicator/code/busy-indicator-progress.ts
  src/stories/src/components/quantity-field/code/quantity-field-default.ts
  src/stories/src/components/quantity-field/quantity-field-args.ts
  src/stories/src/components/quantity-field/quantity-field.mdx
  src/stories/src/components/quantity-field/quantity-field.stories.tsx
  src/stories/src/guides/getting-started.stories.mdx
  src/test/spec/busy-indicator/busy-indicator.spec.ts
  src/test/spec/quantity-field/quantity-field-no-input.fixture.html
  src/test/spec/quantity-field/quantity-field.fixture.html
  src/test/spec/quantity-field/quantity-field.spec.ts
Labels: minor, skip-release, @next

#532 feat(icon-button): create deprecated icon button element for backwards compatibility
  src/dev/pages/icon-button/icon-button.ejs
  src/dev/pages/icon-button/icon-button.ts
  src/lib/deprecated/icon-button/deprecated-icon-button-component-delegate.ts
  src/lib/deprecated/icon-button/deprecated-icon-button-constants.ts
  src/lib/deprecated/icon-button/deprecated-icon-button.html
  src/lib/deprecated/icon-button/deprecated-icon-button.scss
  src/lib/deprecated/icon-button/deprecated-icon-button.test.ts
  src/lib/deprecated/icon-button/deprecated-icon-button.ts
  src/lib/deprecated/icon-button/index.ts
  src/lib/index.ts
Labels: minor, skip-release, @next

#533 fix(field): fixed a bug where the focus indicator was not properly covering the outline
  src/lib/field/_core.variant.scss
Labels: patch, skip-release, @next

#534 feat(calendar): remove MDC, use focus indicator, state-layer, and global tokens
  package-lock.json
  package.json
  src/lib/calendar/_mixins.scss
  src/lib/calendar/_variables.scss
  src/lib/calendar/calendar-constants.ts
  src/lib/calendar/calendar-dom-utils.ts
  src/lib/calendar/calendar-menu/_mixins.scss
  src/lib/calendar/calendar-menu/calendar-menu-adapter.ts
  src/lib/calendar/calendar-menu/calendar-menu-constants.ts
  src/lib/calendar/calendar-menu/calendar-menu-utils.ts
  src/lib/calendar/calendar-menu/calendar-menu.ts
  src/lib/calendar/calendar.ts
  src/test/spec/calendar/calendar.spec.ts
  src/test/spec/date-picker/date-picker.spec.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
Labels: minor, skip-release, @next

#531 feat(bottom-sheet): refactor to use `<forge-dialog>`
  src/dev/pages/bottom-sheet/bottom-sheet.ejs
  src/dev/pages/bottom-sheet/bottom-sheet.scss
  src/dev/pages/bottom-sheet/bottom-sheet.ts
  src/lib/bottom-sheet/_core.scss
  src/lib/bottom-sheet/_mixins.scss
  src/lib/bottom-sheet/_token-utils.scss
  src/lib/bottom-sheet/_variables.scss
  src/lib/bottom-sheet/bottom-sheet-adapter.ts
  src/lib/bottom-sheet/bottom-sheet-constants.ts
  src/lib/bottom-sheet/bottom-sheet-foundation.ts
  src/lib/bottom-sheet/bottom-sheet.html
  src/lib/bottom-sheet/bottom-sheet.scss
  src/lib/bottom-sheet/bottom-sheet.ts
  src/lib/bottom-sheet/build.json
  src/lib/bottom-sheet/index.scss
  src/lib/core/styles/tokens/bottom-sheet/_tokens.scss
  src/lib/dialog/_core.scss
  src/lib/dialog/dialog.scss
  src/stories/src/components/bottom-sheet/bottom-sheet-args.ts
  src/stories/src/components/bottom-sheet/bottom-sheet.stories.tsx
  src/test/spec/bottom-sheet/bottom-sheet.spec.ts
Labels: minor, skip-release, @next

#536 feat(table): refactor to use global tokens and `<forge-checkbox>`
  package-lock.json
  package.json
  src/dev/pages/table/table.ts
  src/lib/checkbox/checkbox-foundation.ts
  src/lib/forge.scss
  src/lib/radio/radio/radio-foundation.ts
  src/lib/switch/switch-foundation.ts
  src/lib/table/_core.scss
  src/lib/table/_mixins.scss
  src/lib/table/_variables.scss
  src/lib/table/forge-table.scss
  src/lib/table/index.scss
  src/lib/table/table-constants.ts
  src/lib/table/table-foundation.ts
  src/lib/table/table-utils.ts
  src/lib/theme/_theme-dark.scss
  src/test/spec/table/table.spec.ts
Labels: minor, skip-release, @next

#537 feat(list): add navlist block margin and tokens; rename text-related tokens in list item
  src/lib/core/styles/tokens/list/list-item/_tokens.scss
  src/lib/core/styles/tokens/list/list/_tokens.scss
  src/lib/list/list-item/_core.scss
  src/lib/list/list-item/list-item.scss
  src/lib/list/list-item/list-item.ts
  src/lib/list/list/list.scss
Labels: minor, skip-release, @next

#538 feat(open-icon): refactor to use tokens, custom rotation values, and custom slotted icons
  src/dev/pages/open-icon/open-icon.ejs
  src/dev/pages/open-icon/open-icon.html
  src/dev/pages/open-icon/open-icon.ts
  src/dev/src/components.json
  src/lib/core/styles/tokens/open-icon/_tokens.scss
  src/lib/open-icon/_core.scss
  src/lib/open-icon/_mixins.scss
  src/lib/open-icon/_token-utils.scss
  src/lib/open-icon/_variables.scss
  src/lib/open-icon/build.json
  src/lib/open-icon/index.scss
  src/lib/open-icon/index.ts
  src/lib/open-icon/open-icon-adapter.ts
  src/lib/open-icon/open-icon-constants.ts
  src/lib/open-icon/open-icon-foundation.ts
  src/lib/open-icon/open-icon.html
  src/lib/open-icon/open-icon.scss
  src/lib/open-icon/open-icon.test.ts
  src/lib/open-icon/open-icon.ts
  src/test/spec/open-icon/open-icon.spec.ts
Labels: minor, skip-release, @next

#539 feat(paginator): refactor to use global tokens and new style patterns
  src/dev/pages/paginator/paginator.ts
  src/lib/paginator/_core.scss
  src/lib/paginator/_mixins.scss
  src/lib/paginator/_variables.scss
  src/lib/paginator/build.json
  src/lib/paginator/index.scss
  src/lib/paginator/paginator-adapter.ts
  src/lib/paginator/paginator-constants.ts
  src/lib/paginator/paginator-foundation.ts
  src/lib/paginator/paginator.html
  src/lib/paginator/paginator.scss
  src/lib/paginator/paginator.test.ts
  src/lib/paginator/paginator.ts
  src/test/spec/paginator/paginator.spec.ts
Labels: minor, skip-release, @next

#542 feat: emit all tokens in global stylesheet
  src/dev/pages/drawer/drawer.scss
  src/dev/pages/focus-indicator/focus-indicator.scss
  src/dev/pages/list/list.scss
  src/dev/pages/overlay/overlay.scss
  src/dev/pages/popover/popover.scss
  src/dev/pages/scaffold/scaffold.scss
  src/dev/pages/skeleton/skeleton.ejs
  src/dev/pages/state-layer/state-layer.scss
  src/dev/pages/table/table.scss
  src/dev/pages/tabs/tabs.scss
  src/dev/pages/toolbar/toolbar.scss
  src/dev/pages/view-switcher/view-switcher.scss
  src/dev/src/styles/_list.scss
  src/lib/app-bar/search/app-bar-search.ts
  src/lib/build.json
  src/lib/core/styles/animation/index.scss
  src/lib/core/styles/border/index.scss
  src/lib/core/styles/elevation/index.scss
  src/lib/core/styles/shape/index.scss
  src/lib/core/styles/spacing/index.scss
  src/lib/core/styles/theme/index.scss
  src/lib/core/styles/tokens/elevation/_tokens.scss
  src/lib/core/styles/tokens/theme/_tokens.core.scss
  src/lib/core/styles/tokens/theme/_tokens.scss
  src/lib/core/styles/tokens/theme/_tokens.status.scss
  src/lib/core/styles/tokens/theme/_tokens.surface.scss
  src/lib/core/styles/tokens/theme/_tokens.text.scss
  src/lib/core/styles/tokens/theme/_tokens.utilities.scss
  src/lib/forge-tokens.scss
  src/lib/forge.scss
  src/stories/preview-head.html
  src/stories/src/components/button/button.mdx
  src/stories/src/components/calendar/calendar.mdx
  src/stories/src/components/card/card.mdx
  src/stories/src/components/chips/chips.mdx
  src/stories/src/components/divider/divider.mdx
  src/stories/src/components/drawer/drawer.mdx
  src/stories/src/components/drawer/drawer.stories.tsx
  src/stories/src/components/file-picker/file-picker.mdx
  src/stories/src/components/split-view/split-view.mdx
  src/stories/src/components/stepper/stepper.mdx
  src/stories/src/components/table/table.mdx
  src/stories/src/components/toolbar/toolbar.mdx
  src/stories/src/core/theme-color-grid.tsx
  src/stories/src/guides/css-custom-properties.stories.mdx
Labels: minor, @next

#543 feat: added month change event for date-picker and date-range-picker
  src/dev/pages/date-picker/date-picker.ts
  src/dev/pages/date-range-picker/date-range-picker.ts
  src/lib/calendar/calendar-constants.ts
  src/lib/core/base/base-adapter.ts
  src/lib/date-picker/base/base-date-picker-adapter.ts
  src/lib/date-picker/base/base-date-picker-foundation.ts
  src/test/spec/date-picker/date-picker.spec.ts
Labels: minor, skip-release

#544 fix(text-field): remove legacy `<label>` & `<input>` DOM order manipulation
  src/dev/pages/autocomplete/autocomplete.ejs
  src/dev/pages/date-range-picker/date-range-picker.ejs
  src/dev/pages/keyboard-shortcut/keyboard-shortcut.ejs
  src/dev/pages/time-picker/time-picker.ejs
  src/dev/src/partials/controls/text-field.ejs
  src/dev/src/partials/controls/time-picker.ejs
  src/lib/field/field-adapter.ts
  src/lib/field/field-foundation.ts
  src/lib/text-field/text-field-adapter.ts
  src/stories/src/components/autocomplete/autocomplete.stories.tsx
  src/stories/src/components/autocomplete/code/autocomplete-default.ts
  src/stories/src/components/date-picker/code/date-picker-default.ts
  src/stories/src/components/date-picker/date-picker.stories.tsx
  src/stories/src/components/date-range-picker/code/date-range-picker-default.ts
  src/stories/src/components/date-range-picker/date-range-picker.stories.tsx
  src/stories/src/components/text-field/code/text-field-default.ts
  src/stories/src/components/text-field/text-field.stories.tsx
  src/stories/src/components/time-picker/code/time-picker-default.ts
  src/stories/src/components/time-picker/time-picker.stories.tsx
  src/stories/src/mock/document-filters.tsx
Labels: patch
