Repository tyler-technologies-oss/forge, pull requests merged in 2024-06, with the labels that each got.

#606 feat: add label value to storybook
  src/lib/split-view/split-view-panel/split-view-panel.ts
  src/stories/components/split-view/split-view-panel/SplitViewPanel.mdx
  src/stories/components/split-view/split-view-panel/SplitViewPanel.scss
  src/stories/components/split-view/split-view-panel/SplitViewPanel.stories.ts
  src/stories/components/split-view/split-view/SplitView.mdx
  src/stories/components/split-view/split-view/SplitView.scss
  src/stories/components/split-view/split-view/SplitView.stories.ts
Labels: minor

#607 feat: add switch to storybook
  src/stories/components/switch/Switch.mdx
  src/stories/components/switch/Switch.stories.ts
Labels: minor

#609 Next storybook refactor time picker
  src/lib/time-picker/time-picker.ts
  src/stories/components/time-picker/TimePicker.mdx
  src/stories/components/time-picker/TimePicker.stories.ts
Labels: minor

#610 feat: add add view switcher
  src/stories/components/view-switcher/ViewSwitcher.mdx
  src/stories/components/view-switcher/ViewSwitcher.scss
  src/stories/components/view-switcher/ViewSwitcher.stories.ts
Labels: minor

#611 feat: add date range picker to storybook
  src/lib/date-range-picker/date-range-picker.ts
  src/stories/components/date-range-picker/DateRangePicker.mdx
  src/stories/components/date-range-picker/DateRangePicker.stories.ts
Labels: minor

#612 chore: add paginator
  src/stories/components/paginator/Paginator.stories.ts
Labels: skip-release

#613 feat: add page state to storybook
  src/stories/components/page-state/PageState.mdx
  src/stories/components/page-state/PageState.stories.ts
Labels: minor

#608 feat: storybook refactor color picker
  src/lib/color-picker/color-picker.ts
  src/stories/components/color-picker/ColorPicker.stories.ts
Labels: minor

#614 Next storybook refactor date picker
  src/lib/date-picker/base/base-date-picker.ts
  src/lib/date-picker/date-picker.ts
  src/stories/components/date-picker/DatePicker.stories.ts
Labels: minor

#615 Next storybook refactor calendar 2
  src/lib/calendar/calendar-adapter.ts
  src/lib/calendar/calendar.ts
  src/stories/components/calendar/Calendar.stories.ts
Labels: minor

#616 fix: fixed accessibility issues with popups
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-foundation.ts
  src/lib/core/utils/utils.ts
  src/lib/date-picker/date-picker-adapter.ts
  src/lib/date-range-picker/date-range-picker-adapter.ts
  src/lib/list-dropdown/list-dropdown-constants.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/list/list-item/list-item-adapter.ts
  src/lib/menu/menu-adapter.ts
  src/lib/menu/menu-foundation.ts
  src/lib/select/core/base-select-adapter.ts
  src/lib/select/core/base-select-foundation.ts
  src/lib/select/option/option.ts
  src/lib/select/select-dropdown/select-dropdown-adapter.ts
  src/lib/select/select/select-adapter.ts
  src/lib/select/select/select-foundation.ts
  src/lib/time-picker/time-picker-adapter.ts
  src/lib/time-picker/time-picker-foundation.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
  src/test/spec/select/select-dropdown.spec.ts
  src/test/spec/select/select.spec.ts
Labels: bug, patch, skip-release, accessibility

#618 fix: fixed accessibility issues with dynamic popover dropdowns
  .github/workflows/deploy-pr.yml
  package-lock.json
  package.json
  src/dev/pages/autocomplete/autocomplete.ejs
  src/dev/src/components.json
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/autocomplete/autocomplete-core.ts
  src/lib/core/utils/utils.ts
  src/lib/date-picker/date-picker-adapter.ts
  src/lib/date-range-picker/date-range-picker-adapter.ts
  src/lib/list-dropdown/list-dropdown-constants.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/menu/menu-adapter.ts
  src/lib/menu/menu-core.ts
  src/lib/select/core/base-select-core.ts
  src/lib/select/select/select-adapter.ts
  src/lib/select/select/select.test.ts
  src/lib/time-picker/time-picker-adapter.ts
  src/lib/time-picker/time-picker-core.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
Labels: patch, @next

#620 feat: update forge-core dep and other minor fixes
  package-lock.json
  package.json
  src/lib/badge/badge-component-delegate.ts
  src/lib/badge/index.ts
  src/lib/button/_core.scss
  src/lib/inline-message/_core.scss
  src/lib/list/list-item/list-item-constants.ts
  src/stories/components/button/Button.stories.ts
Labels: minor, @next

#621 Origin/fix tab accessibility issues
  src/dev/pages/autocomplete/autocomplete.ejs
  src/dev/pages/tab-bar/tab-bar.ejs
  src/dev/src/partials/header.ejs
  src/lib/tabs/tab/_mixins.scss
  src/lib/tabs/tab/tab-adapter.ts
  src/lib/tabs/tab/tab-constants.ts
  src/lib/tabs/tab/tab-foundation.ts
  src/lib/tabs/tab/tab.html
  src/lib/tabs/tab/tab.scss
  src/lib/tabs/tab/tab.ts
  src/stories/src/components/tab-bar/tab-bar.mdx
  src/test/spec/tabs/tab-bar.spec.ts
Labels: patch, accessibility

#625 fix(field): slotted elements can fill entire block size of field
  src/dev/pages/field/field.ts
  src/lib/field/_core.scss
  src/lib/field/field.html
Labels: patch, skip-release

#626 fix(tab-bar): move ARIA attributes to internal scroll container for tab bar
  src/lib/tabs/tab-bar/tab-bar-adapter.ts
  src/lib/tabs/tab-bar/tab-bar-constants.ts
  src/lib/tabs/tab-bar/tab-bar-core.ts
  src/lib/tabs/tab-bar/tab-bar.html
  src/lib/tabs/tab-bar/tab-bar.ts
  src/lib/tabs/tabs.test.ts
  src/stories/components/tabs/Tabs.stories.ts
Labels: patch, skip-release, accessibility

#628 docs: fix image paths and CSS formatting in doc block code snippets
  package-lock.json
  package.json
  src/stories/components/avatar/Avatar.stories.ts
  src/stories/components/chips/Chips.stories.ts
  src/stories/decorators.ts
Labels: documentation, skip-release

#629 chore: remove legacy `@tylertech/forge-testing` dependency
  .github/workflows/build-release.yml
  package-lock.json
  package.json
  src/lib/accordion/accordion-adapter.ts
  src/lib/accordion/accordion-core.ts
  src/lib/accordion/accordion.test.ts
  src/lib/accordion/accordion.ts
  src/lib/app-bar/profile-button/app-bar-profile-button.test.ts
  src/lib/app-bar/search/app-bar-search.test.ts
  src/lib/avatar/avatar.test.ts
  src/lib/backdrop/backdrop.test.ts
  src/lib/banner/banner.test.ts
  src/lib/button-area/button-area.test.ts
  src/lib/button-toggle/button-toggle/button-toggle-core.ts
  src/lib/button/base/base-button-core.ts
  src/lib/chip-field/chip-field.test.ts
  src/lib/core/testing/pointer.ts
  src/lib/core/utils/dismissible-stack.ts
  src/lib/core/utils/event-utils.ts
  src/lib/core/utils/utils.ts
  src/lib/dialog/dialog.test.ts
  src/lib/expansion-panel/expansion-panel.test.ts
  src/lib/field/field.test.ts
  src/lib/icon/icon.test.ts
  src/lib/label/label-core.ts
  src/lib/popover/popover.test.ts
  src/lib/radio/core/radio-group-manager.ts
  src/lib/radio/radio-group/radio-group.test.ts
  src/lib/radio/radio/radio-core.ts
  src/lib/select/select/select.test.ts
  src/lib/state-layer/state-layer.test.ts
  src/lib/tabs/tabs.test.ts
  src/lib/text-field/text-field.test.ts
  src/lib/toast/toast.test.ts
  src/lib/tooltip/tooltip.test.ts
  src/stories/blocks/CustomArgTypes.tsx
  src/stories/components/inline-message/InlineMessage.stories.ts
  src/test/spec/accordion/accordion.spec.ts
  src/test/spec/autocomplete/autocomplete.spec.ts
  src/test/spec/bottom-sheet/bottom-sheet.spec.ts
  src/test/spec/calendar/calendar.spec.ts
  src/test/spec/color-picker/color-picker.spec.ts
  src/test/spec/date-picker/calendar-dropdown.spec.ts
  src/test/spec/date-picker/date-picker.spec.ts
  src/test/spec/date-range-picker/date-range-picker.spec.ts
  src/test/spec/drawer/drawer.spec.ts
  src/test/spec/drawer/modal-drawer.spec.ts
  src/test/spec/keyboard-shortcut/keyboard-shortcut.spec.ts
  src/test/spec/list-dropdown/list-dropdown-test-utils.ts
  src/test/spec/list-dropdown/list-dropdown.spec.ts
  src/test/spec/menu/menu.spec.ts
  src/test/spec/select/select-component-delegate.spec.ts
  src/test/spec/select/select-dropdown.spec.ts
  src/test/spec/split-view/split-view-panel/split-view-panel.spec.ts
  src/test/spec/split-view/split-view/split-view.spec.ts
  src/test/spec/stepper/stepper.spec.ts
  src/test/spec/table/table.spec.ts
  src/test/spec/time-picker/time-picker.spec.ts
  src/test/spec/view-switcher/view-switcher.spec.ts
Labels: skip-release

#632 fix(forge-step): correct select event name for proper typing
  src/dev/pages/stepper/stepper.ts
  src/lib/stepper/step/step.ts
Labels: patch

#636 feat(select): native form association and label awareness
  src/dev/pages/select/select.ejs
  src/lib/button-toggle/button-toggle-group/button-toggle-group.ts
  src/lib/button/base/base-button.ts
  src/lib/constants.ts
  src/lib/core/mixins/focus/with-focusable.ts
  src/lib/core/mixins/label/with-label-aware.ts
  src/lib/label/label-adapter.ts
  src/lib/label/label-constants.ts
  src/lib/label/label-core.ts
  src/lib/label/label.test.ts
  src/lib/label/label.ts
  src/lib/radio/radio-group/radio-group.ts
  src/lib/select/select/select-adapter.ts
  src/lib/select/select/select-core.ts
  src/lib/select/select/select.test.ts
  src/lib/select/select/select.ts
Labels: minor, skip-release
