Repository tyler-technologies-oss/forge, pull requests merged in 2024-05, with the labels that each got.

#546 feat(app-bar): add new cancelable `forge-app-bar-navigate` event to prevent navigation when anchor is clicked
  src/lib/app-bar/app-bar/app-bar-adapter.ts
  src/lib/app-bar/app-bar/app-bar-constants.ts
  src/lib/app-bar/app-bar/app-bar-foundation.ts
  src/lib/app-bar/app-bar/app-bar.test.ts
Labels: minor, skip-release, @next

#547 feat(slider): separate default events from range events and update default event detail structure to use object with value property
  src/dev/pages/slider/slider.ts
  src/lib/slider/slider-component-delegate.ts
  src/lib/slider/slider-constants.ts
  src/lib/slider/slider-foundation.ts
  src/lib/slider/slider.test.ts
  src/lib/slider/slider.ts
Labels: minor, skip-release, @next

#550 fix(paginator): add/remove tooltips when paging buttons are added/removed
  src/lib/paginator/paginator-adapter.ts
  src/lib/paginator/paginator-constants.ts
  src/lib/paginator/paginator.html
Labels: patch, @next

#553 chore: update workflows to use node 20
  .github/workflows/auto-pr-check.yml
  .github/workflows/build-pr.yml
  .github/workflows/build-release.yml
  .github/workflows/cleanup-pr.yml
  .github/workflows/deploy-pr.yml
Labels: skip-release, @next

#554 fix(app-bar): fix typings for navigate event
  src/lib/app-bar/app-bar/app-bar.ts
Labels: patch, skip-release, @next

#551 fix(list-item): removed legacy internal mousedown handler that was preventing pointer events if already focused
  src/lib/list/list-item/list-item-foundation.ts
Labels: patch

#556 fix(linear-progress): fixed buffering styles
  src/lib/core/styles/tokens/linear-progress/_tokens.scss
  src/lib/linear-progress/_core.scss
  src/lib/linear-progress/linear-progress-adapter.ts
  src/lib/linear-progress/linear-progress-constants.ts
  src/lib/linear-progress/linear-progress.html
  src/lib/linear-progress/linear-progress.scss
  src/lib/linear-progress/linear-progress.test.ts
Labels: patch, skip-release, @next

#558 fix(table): fixed a bug where the table sort icon rotation could get out sync
  src/lib/table/table-foundation.ts
  src/stories/src/components/table/table.mdx
Labels: patch, skip-release

#559 feat(list-item): add `deactivateRipple()` method to allow for manually removing the "pressed" ripple state if needed
  src/lib/list/list-item/list-item-foundation.ts
  src/lib/list/list-item/list-item.ts
  src/stories/src/components/list/list.mdx
Labels: minor

#560 feat(overlay): upgrade to latest `@floating-ui/dom` and remove custom top-layer middleware
  package-lock.json
  package.json
  src/lib/core/utils/position-utils.ts
  src/lib/overlay/overlay-adapter.ts
Labels: minor, skip-release, @next

#562 fix(select): fix missing `aria-controls` attribute to use temporary element
  src/lib/select/option/option.ts
  src/lib/select/select-dropdown/select-dropdown-adapter.ts
  src/lib/select/select/select-adapter.ts
Labels: patch, skip-release, @next

#561 chore: fix CEM for elements that extends mixins
  package-lock.json
  package.json
  src/lib/bottom-sheet/bottom-sheet.ts
  src/lib/button-toggle/button-toggle-group/button-toggle-group.ts
  src/lib/button-toggle/button-toggle/button-toggle.ts
  src/lib/button/base/base-button.ts
  src/lib/checkbox/checkbox.ts
  src/lib/core/controllers/move-controller.ts
  src/lib/dialog/dialog.ts
  src/lib/field/base/base-field.ts
  src/lib/field/base/with-base-field.ts
  src/lib/list/list-item/list-item.ts
  src/lib/popover/popover-foundation.ts
  src/lib/radio/radio-group/radio-group.ts
  src/lib/radio/radio/radio.ts
  src/lib/select/select/select.ts
  src/lib/switch/switch.ts
  src/lib/toast/toast.ts
  src/lib/tooltip/tooltip-foundation.ts
  src/lib/tooltip/tooltip.ts
Labels: patch, skip-release, @next

#563 feat(base-button): remove internal `<a>` support and APIs and instead allow for slotted `<a>` elements and update each button-like element to support slotted anchor styling/functionality
  src/dev/pages/button/button.ejs
  src/dev/pages/button/button.html
  src/dev/pages/button/button.ts
  src/dev/pages/fab/fab.ejs
  src/dev/pages/icon-button/icon-button.ejs
  src/dev/pages/typography/typography.ejs
  src/dev/src/components.json
  src/lib/button/_core.scss
  src/lib/button/base/base-button-adapter.ts
  src/lib/button/base/base-button-constants.ts
  src/lib/button/base/base-button-foundation.ts
  src/lib/button/base/base-button.test.ts
  src/lib/button/base/base-button.ts
  src/lib/button/button.scss
  src/lib/core/styles/typography/index.scss
  src/lib/deprecated/button/deprecated-button.scss
  src/lib/floating-action-button/_core.scss
  src/lib/floating-action-button/floating-action-button.scss
  src/lib/icon-button/_core.scss
  src/lib/icon-button/icon-button.scss
  src/lib/state-layer/state-layer-foundation.ts
Labels: minor, skip-release, @next

#565 fix(button-toggle): update height to match standard button
  src/lib/button-toggle/button-toggle-group/_core.scss
  src/lib/core/styles/tokens/button-toggle/button-toggle/_tokens.scss
Labels: patch, skip-release, @next

#564 feat(autocomplete): add popoverExpanded prop/attr to base field and update autocomplete to use it
  src/dev/pages/autocomplete/autocomplete.ejs
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/field/base/base-field-constants.ts
  src/lib/field/base/base-field-foundation.ts
  src/lib/field/base/base-field.ts
  src/lib/field/field-constants.ts
Labels: minor, skip-release, @next

#566 feat: rename tabs and list-item leading/trailing (deprecated) slots to start/end
  src/dev/pages/list/list.ejs
  src/dev/pages/tabs/tabs.html
  src/dev/pages/tabs/tabs.ts
  src/lib/core/styles/tokens/list/list-item/_tokens.scss
  src/lib/list/list-item/_core.scss
  src/lib/list/list-item/list-item-adapter.ts
  src/lib/list/list-item/list-item-constants.ts
  src/lib/list/list-item/list-item-foundation.ts
  src/lib/list/list-item/list-item.html
  src/lib/list/list-item/list-item.scss
  src/lib/list/list-item/list-item.ts
  src/lib/list/list.test.ts
  src/lib/tabs/tab/tab.html
  src/lib/tabs/tab/tab.scss
  src/lib/tabs/tab/tab.ts
Labels: minor

#568 fix(badge): ellipse overflowing text content
  src/lib/badge/_core.scss
  src/lib/badge/badge.html
  src/lib/badge/badge.scss
Labels: patch, skip-release, @next

#569 fix(button): remove unused JSDoc for anchor-specific attrs
  src/lib/autocomplete/autocomplete-adapter.ts
  src/lib/avatar/avatar.ts
  src/lib/button/base/base-button-adapter.ts
  src/lib/button/base/base-button.ts
  src/lib/button/button.ts
  src/lib/floating-action-button/floating-action-button.ts
  src/lib/icon-button/icon-button.ts
Labels: patch, @next

#567 fix(app-bar-notification-button): fixed a bug where the badge count could not be unset and updated the logic to not render the count
  src/lib/app-bar/notification-button/app-bar-notification-button-adapter.ts
  src/lib/app-bar/notification-button/app-bar-notification-button-foundation.ts
  src/lib/app-bar/notification-button/app-bar-notification-button.ts
  src/stories/src/components/app-bar-notifications/app-bar-notifications.mdx
  src/test/spec/app-bar/notification-button/app-bar-notification-button.spec.ts
Labels: patch, skip-release

#573 fix(menu): fixed a bug where pressing the tab key would select the active option
  src/lib/menu/menu-foundation.ts
  src/stories/src/components/menu/menu.mdx
  src/test/spec/menu/menu.spec.ts
Labels: patch

#579 Next storybook refactor accordion
  src/stories/components/accordion/Accordion.mdx
  src/stories/components/accordion/Accordion.scss
  src/stories/components/accordion/Accordion.stories.ts
Labels: minor

#574 Next storybook refactor banner
  src/lib/core/styles/tokens/button/_tokens.scss
  src/stories/components/banner/Banner.mdx
  src/stories/components/banner/Banner.stories.ts
Labels: minor

#586 feat: add card storybook
  src/lib/card/card.ts
  src/stories/components/card/Card.mdx
  src/stories/components/card/Card.scss
  src/stories/components/card/Card.stories.ts
Labels: minor

#585 feat: add skeleton storybook
  src/stories/components/skeleton/Skeleton.mdx
  src/stories/components/skeleton/Skeleton.stories.ts
Labels: minor

#582 feat: add app-bar storybook
  src/lib/app-bar/help-button/app-bar-help-button.ts
  src/lib/app-bar/menu-button/app-bar-menu-button.ts
  src/lib/app-bar/notification-button/app-bar-notification-button-foundation.ts
  src/lib/app-bar/notification-button/app-bar-notification-button.ts
  src/lib/app-bar/profile-button/app-bar-profile-button.ts
  src/lib/app-bar/search/app-bar-search.ts
  src/stories/components/app-bar/AppBar.mdx
  src/stories/components/app-bar/AppBar.scss
  src/stories/components/app-bar/AppBar.stories.ts
  src/stories/components/app-bar/Search/search.mdx
  src/stories/components/app-bar/Search/search.stories.ts
  src/stories/components/app-bar/help-button/HelpButton.mdx
  src/stories/components/app-bar/help-button/HelpButton.stories.ts
  src/stories/components/app-bar/menu-button/MenuButton.mdx
  src/stories/components/app-bar/menu-button/MenuButton.stories.ts
  src/stories/components/app-bar/notifications/notifications.mdx
  src/stories/components/app-bar/notifications/notifications.stories.ts
  src/stories/components/app-bar/profile/profile.mdx
  src/stories/components/app-bar/profile/profile.stories.ts
Labels: minor

#589 feat: add inline messages to storybook
  src/stories/components/inline-message/InlineMessage.mdx
  src/stories/components/inline-message/InlineMessage.stories.ts
Labels: minor

#590 feat: add linear progress storybook
  src/lib/linear-progress/linear-progress.ts
  src/stories/components/inline-message/InlineMessage.mdx
  src/stories/components/linear-progress/LinearProgress.mdx
  src/stories/components/linear-progress/LinearProgress.stories.ts
Labels: minor

#581 refactor(field): refactor styles
  src/dev/pages/field/field.html
  src/dev/pages/field/field.ts
  src/dev/pages/text-field/text-field.html
  src/dev/pages/text-field/text-field.ts
  src/lib/chip-field/chip-field.html
  src/lib/core/styles/tokens/field/_tokens.scss
  src/lib/field/_core.animation.scss
  src/lib/field/_core.layout.scss
  src/lib/field/_core.scss
  src/lib/field/_core.shape.scss
  src/lib/field/_core.slotted.scss
  src/lib/field/_core.state.scss
  src/lib/field/_core.theme.scss
  src/lib/field/_core.variant.scss
  src/lib/field/base/base-field-constants.ts
  src/lib/field/field-adapter.ts
  src/lib/field/field-constants.ts
  src/lib/field/field-foundation.ts
  src/lib/field/field.html
  src/lib/field/field.scss
  src/lib/field/field.test.ts
  src/lib/field/field.ts
  src/lib/select/select/select.html
  src/lib/text-field/text-field-component-delegate.ts
  src/lib/text-field/text-field.html
  src/lib/text-field/text-field.ts
Labels: minor, skip-release, @next

#591 feat: add open icon storybook
  src/lib/open-icon/open-icon.ts
  src/stories/components/open-icon/OpenIcon.mdx
  src/stories/components/open-icon/OpenIcon.stories.ts
Labels: minor

#587 feat(popover): enable `autofocus` attribute when triggered via either keyboard or pointer
  src/lib/popover/popover-adapter.ts
  src/lib/popover/popover-foundation.ts
  src/lib/popover/popover.test.ts
Labels: minor, skip-release, @next

#592 fix(field): clean up autofill animation styles
  src/lib/chip-field/chip-field.test.ts
  src/lib/field/_core.layout.scss
  src/lib/field/_core.scss
  src/lib/field/_core.slotted.scss
  src/lib/field/field.scss
Labels: patch, skip-release, @next

#594 fix(menu): fixed a bug where the focus indicator was activating when clicking on forge buttons
  src/lib/menu/menu-adapter.ts
Labels: patch, skip-release, @next

#580 feat: storybook refactor list
  src/lib/list/list-item/list-item.ts
  src/lib/list/list/list.ts
  src/stories/components/list/List.mdx
  src/stories/components/list/List.stories.ts
Labels: minor

#593 Next storybook refactor button area
  src/lib/button-area/button-area.ts
  src/stories/components/button-area/ButtonArea.scss
  src/stories/components/button-area/ButtonArea.stories.ts
Labels: minor

#595 feat: add menu to storybook
  src/stories/components/menu/Menu.mdx
  src/stories/components/menu/Menu.stories.ts
  src/stories/utils.ts
Labels: minor

#597 fix(radio): set aria-required on radio group element instead of individual radios
  src/lib/radio/core/radio-group-manager.ts
  src/lib/radio/radio-group/radio-group-adapter.ts
  src/lib/radio/radio-group/radio-group-foundation.ts
  src/lib/radio/radio-group/radio-group.test.ts
  src/lib/radio/radio/radio-adapter.ts
  src/lib/radio/radio/radio-foundation.ts
  src/lib/radio/radio/radio.ts
Labels: patch, skip-release, @next, accessibility

#598 feat: storybook refactor checkbox
  src/lib/checkbox/checkbox.ts
  src/stories/components/checkbox/Checkbox.stories.ts
Labels: minor

#596 Next storybook refactor button toggle
  src/lib/button-toggle/button-toggle-group/button-toggle-group.ts
  src/lib/button-toggle/button-toggle/button-toggle.ts
  src/stories/components/button-toggle/ButtonToggle.mdx
  src/stories/components/button-toggle/ButtonToggle.stories.ts
Labels: minor

#601 feat: add profile card
  src/stories/components/profile-card/ProfileCard.mdx
  src/stories/components/profile-card/ProfileCard.stories.ts
Labels: minor

#600 Next storybook refactor toolbar
  src/lib/toolbar/toolbar.ts
  src/stories/components/toolbar/Toolbar.mdx
  src/stories/components/toolbar/Toolbar.stories.ts
Labels: minor

#599 feat: add stepper/step to storybook
  src/lib/stepper/step/_core.scss
  src/lib/stepper/step/step.scss
  src/lib/stepper/stepper/stepper.ts
  src/stories/components/menu/Menu.stories.ts
  src/stories/components/stepper/step/Step.mdx
  src/stories/components/stepper/step/Step.stories.ts
  src/stories/components/stepper/stepper/Stepper.mdx
  src/stories/components/stepper/stepper/Stepper.stories.ts
Labels: minor

#602 feat: add radios to storybook
  src/stories/components/radio/Radio.mdx
  src/stories/components/radio/Radio.stories.ts
  src/stories/components/radio/radio-group/RadioGroup.mdx
  src/stories/components/radio/radio-group/RadioGroup.stories.ts
Labels: minor

#603 feat: add scaffold
  src/stories/components/scaffold/Scaffold.mdx
  src/stories/components/scaffold/Scaffold.scss
  src/stories/components/scaffold/Scaffold.stories.ts
Labels: minor
