Repository tyler-technologies-oss/forge, pull requests merged in 2025-03, with the labels that each got.

#858 docs: add support for grouped menu options in documentation and stories
  src/stories/components/menu/Menu.mdx
  src/stories/components/menu/Menu.stories.ts
Labels: documentation, skip-release

#856 fix(field): ensure that enabled field inputs use the text cursor
  src/lib/field/_core.scss
Labels: patch, skip-release

#851 feat(menu): added support for option tooltips
  src/dev/pages/menu/menu.ts
  src/dev/src/partials/options-drawer.ejs
  src/dev/src/styles/_options.scss
  src/lib/list-dropdown/list-dropdown-constants.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/menu/menu-constants.ts
  src/lib/menu/menu-core.ts
  src/lib/menu/menu.ts
  src/lib/select/core/base-select-adapter.ts
  src/lib/select/option/option-constants.ts
  src/lib/select/option/option-core.ts
  src/lib/select/option/option.ts
  src/lib/switch/switch.ts
Labels: minor, skip-release

#861 fix(field): do not show required asterisk if no label is present
  src/lib/field/field.scss
Labels: patch, skip-release

#860 fix(list-item): improve overflow handling on slotted `<button>` elements
  src/lib/list/list-item/_core.scss
  src/lib/list/list-item/list-item.scss
Labels: patch, skip-release

#859 fix(tabs): fixed a bug where the scroll buttons were not being shown/hidden when tabs are dynamically added/removed
  src/lib/tabs/tab-bar/tab-bar-core.ts
  src/lib/tabs/tabs.test.ts
Labels: patch, skip-release

#846 feat(field): expose `class="outline"` element as a CSS part
  src/lib/field/base/base-field.ts
  src/lib/field/field-constants.ts
  src/lib/field/field.html
  src/lib/field/field.ts
  src/lib/select/select/select.ts
  src/lib/text-field/text-field.ts
Labels: minor

#872 docs: fix demo style code formatting
  src/stories/decorators.ts
Labels: documentation, skip-release

#864 chore: move `toggleState()` helper to general utils and export from lib
  src/lib/core/utils/a11y-utils.ts
  src/lib/core/utils/utils.ts
  src/lib/meter/meter-group/meter-group.ts
  src/lib/meter/meter/meter.ts
Labels: patch, skip-release

#863 fix(avatar): hide text when image is rendered
  src/lib/avatar/avatar.test.ts
  src/lib/avatar/avatar.ts
Labels: patch

#866 feat(dialog): automatically apply `height: auto` to slotted `<forge-scaffold>`
  src/dev/pages/dialog/dialog.scss
  src/lib/dialog/dialog.scss
  src/lib/dialog/forge-dialog.scss
Labels: minor, skip-release

#876 chore: revert `eslint-config-prettier` version upgrade
  package-lock.json
  package.json
Labels: skip-release

#867 fix(button): use grid layout instead of flex to avoid text nodes collapsing
  src/lib/button/_core.scss
  src/lib/core/styles/tokens/button/_tokens.scss
Labels: patch, skip-release

#869 fix(dialog): use capturing keydown listener
  src/lib/dialog/dialog-core.ts
Labels: patch, skip-release

#874 feat(card): refactor to use Lit
  src/lib/avatar/avatar-constants.ts
  src/lib/avatar/avatar.ts
  src/lib/card/card-constants.ts
  src/lib/card/card.html
  src/lib/card/card.scss
  src/lib/card/card.test.ts
  src/lib/card/card.ts
  src/lib/card/index.ts
Labels: minor, skip-release, storybook-preview

#880 fix(app-bar-profile-button): adjust default tooltip placement
  src/lib/app-bar/profile-button/app-bar-profile-button.html
Labels: patch, skip-release

#881 fix(profile-card): focus profile button before sign out button if available
  src/lib/profile-card/profile-card-core.ts
Labels: patch, skip-release

#886 chore: demo cleanup
  src/dev/pages/table/table.ts
  src/stories/components/autocomplete/Autocomplete.stories.ts
Labels: documentation, skip-release

#884 fix(list-item): fix regression related to slotted `<button>` width applying to other child elements
  src/lib/list/list-item/list-item.scss
Labels: patch, skip-release

#885 fix(switch): improve contrast when disabled
  src/lib/core/styles/tokens/switch/_tokens.scss
Labels: patch, skip-release

#878 docs(paginator): add docs about the alternative variant
  src/stories/components/paginator/Paginator.mdx
  src/stories/components/paginator/Paginator.stories.ts
Labels: documentation, skip-release

#879 feat(badge): refactor to use Lit
  src/dev/pages/app-bar/app-bar.ejs
  src/lib/app-bar/notification-button/app-bar-notification-button-adapter.ts
  src/lib/app-bar/notification-button/app-bar-notification-button.ts
  src/lib/badge/badge-component-delegate.ts
  src/lib/badge/badge-constants.ts
  src/lib/badge/badge.html
  src/lib/badge/badge.scss
  src/lib/badge/badge.test.ts
  src/lib/badge/badge.ts
  src/lib/badge/index.ts
  src/stories/components/badge/Badge.stories.ts
Labels: minor, skip-release

#887 chore(stepper-constants): fix to set explicit index type for compatibility
  src/lib/stepper/stepper/stepper-constants.ts
Labels: skip-release

#892 fix(select): fix duplicate `label` CSS part
  src/lib/select/select/select.html
  src/lib/select/select/select.test.ts
Labels: patch, skip-release, storybook-preview

#890 chore: fix lint warning due to typescript compatibility with legacy shared lint rules package
  package-lock.json
  package.json
Labels: skip-release, dependencies

#889 fix: enable Lit-based component compatibility with Forge `@customElement` decorator
  src/lib/avatar/avatar.ts
  src/lib/badge/badge.ts
  src/lib/card/card.ts
  src/lib/key/key-item/index.ts
  src/lib/key/key-item/key-item.ts
  src/lib/key/key/index.ts
  src/lib/key/key/key.ts
  src/lib/meter/meter-group/index.ts
  src/lib/meter/meter-group/meter-group.ts
  src/lib/meter/meter/meter.ts
Labels: patch, skip-release

#888 fix(dialog): update accessible label and description handling for improved ARIA support
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-constants.ts
  src/lib/dialog/dialog.html
  src/lib/dialog/dialog.test.ts
Labels: patch, skip-release, accessibility, storybook-preview

#875 feat(dialog): add "reason" for why dialog is about to close to event `detail`
  src/lib/dialog/dialog-constants.ts
  src/lib/dialog/dialog-core.ts
  src/lib/dialog/dialog.test.ts
  src/lib/dialog/dialog.ts
Labels: minor, skip-release
