Repository tyler-technologies-oss/forge, pull requests merged in 2025-02, with the labels that each got.

#806 docs: fix google analytics tracking for preview pages
  .storybook/addons/google-analytics/register.js
  .storybook/main.ts
  .storybook/manager-head.html
  package-lock.json
  package.json
Labels: skip-release, storybook-preview

#801 fix(table): only apply `aria-hidden` on `<th>` elements if `headerTemplate` is not used
  src/lib/table/table-utils.ts
  src/test/spec/table/table.spec.ts
Labels: patch, skip-release

#802 chore(test): filter Lit dev mode warning from test output
  web-test-runner.config.mjs
Labels: skip-release, tests

#804 docs(view-all): fix exception in view-all hidden docs page
  src/stories/components/view-all/ViewAll.mdx
  src/stories/components/view-all/ViewAll.stories.ts
Labels: documentation, skip-release, storybook-preview

#811 fix(toolbar): move internal `tablist` role to host element
  src/lib/tabs/tab-bar/tab-bar-adapter.ts
  src/lib/tabs/tab-bar/tab-bar-constants.ts
  src/lib/tabs/tab-bar/tab-bar-core.ts
  src/lib/tabs/tab-bar/tab-bar.html
  src/lib/tabs/tab-bar/tab-bar.ts
  src/lib/tabs/tabs.test.ts
Labels: patch, skip-release, accessibility, storybook-preview

#803 fix: exposed `align` token and fixed layout bug with long labels for checkbox, radio, and switch
  src/lib/checkbox/_core.scss
  src/lib/checkbox/checkbox.ts
  src/lib/core/styles/tokens/checkbox/_tokens.scss
  src/lib/core/styles/tokens/radio/_tokens.scss
  src/lib/core/styles/tokens/switch/_tokens.scss
  src/lib/radio/radio/_core.scss
  src/lib/radio/radio/radio.ts
  src/lib/switch/_core.scss
  src/lib/switch/switch.ts
Labels: patch, skip-release

#809 fix(button-area): force root element to match size of host
  src/lib/button-area/_core.scss
Labels: bug, patch, skip-release

#814 fix(tab-bar): setting `activeTab` property will no longer focus the tab
  src/lib/button/base/base-button-adapter.ts
  src/lib/tabs/tab-bar/tab-bar-adapter.ts
  src/lib/tabs/tab-bar/tab-bar-core.ts
  src/lib/tabs/tabs.test.ts
Labels: patch, skip-release

#813 docs(vue): add compiler config
  src/stories/frameworks/Vue.mdx
Labels: documentation, skip-release

#812 feat(avatar): convert to Lit
  src/lib/app-bar/profile-button/app-bar-profile-button.ts
  src/lib/avatar/avatar-adapter.ts
  src/lib/avatar/avatar-constants.ts
  src/lib/avatar/avatar-core.ts
  src/lib/avatar/avatar.html
  src/lib/avatar/avatar.test.ts
  src/lib/avatar/avatar.ts
  src/lib/avatar/index.ts
  src/lib/profile-card/profile-card.ts
  src/stories/components/avatar/Avatar.stories.ts
Labels: minor, skip-release

#810 feat(dialog): adjust default a11y semantics and add new `label` and `description` APIs for providing ARIA info
  src/dev/pages/dialog/dialog-template-basic.ejs
  src/dev/pages/dialog/dialog.ejs
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-constants.ts
  src/lib/dialog/dialog-core.ts
  src/lib/dialog/dialog.scss
  src/lib/dialog/dialog.test.ts
  src/lib/dialog/dialog.ts
  src/stories/components/dialog/Dialog.mdx
  src/stories/components/dialog/Dialog.stories.ts
  src/stories/components/dialog/Dialog.ts
Labels: minor, skip-release, accessibility, storybook-preview

#818 chore: remove unintentional `fit` usage
  src/test/spec/date-picker/date-picker.spec.ts
Labels: skip-release, tests

#816 feat(dialog): add `mode` to global configuration
  src/lib/dialog/dialog-core.ts
  src/lib/dialog/dialog.ts
Labels: minor, skip-release

#815 feat(switch): add new `checked` property/attribute and deprecate `on` property
  src/dev/pages/switch/switch.ejs
  src/dev/src/partials/controls/switch.ejs
  src/lib/switch/switch-adapter.ts
  src/lib/switch/switch-component-delegate.ts
  src/lib/switch/switch-constants.ts
  src/lib/switch/switch-core.ts
  src/lib/switch/switch.test.ts
  src/lib/switch/switch.ts
  src/stories/components/switch/Switch.mdx
  src/stories/components/switch/Switch.stories.ts
Labels: minor, skip-release

#817 feat(icon-button): add new `pressed` property/attribute and deprecate `on` property
  src/dev/pages/switch/switch.ejs
  src/lib/icon-button/icon-button-constants.ts
  src/lib/icon-button/icon-button-core.ts
  src/lib/icon-button/icon-button.scss
  src/lib/icon-button/icon-button.test.ts
  src/lib/icon-button/icon-button.ts
  src/lib/switch/switch.scss
  src/stories/components/icon-button/IconButton.stories.ts
Labels: minor

#820 fix(dialog): reuse internal accessible elements if `label` or `description` change dynamically
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-constants.ts
  src/lib/dialog/dialog.test.ts
Labels: patch, skip-release

#819 fix(autocomplete): traverse composed slots when locating input element
  src/lib/autocomplete/autocomplete-adapter.ts
Labels: patch

#823 fix(dialog): fixed escape key bug when persistent and improved destroy logic
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-core.ts
Labels: patch, skip-release

#824 fix(text-field): fixed a bug where the internal value change listener was not safely guarding types
  src/lib/core/utils/utils.ts
  src/lib/text-field/text-field-core.ts
Labels: patch

#826 chore(select): fix test syntax
  src/lib/select/select/select.test.ts
Labels: skip-release

#841 docs(badge): remove unnecessary style in demo code snippet
  src/stories/components/badge/Badge.stories.ts
Labels: documentation, skip-release

#842 fix(field): only apply hover state when cursor is over container
  src/lib/field/field.scss
Labels: patch, skip-release

#825 fix(dialog): only force-capture focus when modal
  package-lock.json
  package.json
  src/lib/dialog/dialog-adapter.ts
  src/lib/dialog/dialog-core.ts
  src/lib/dialog/dialog.test.ts
  src/lib/dialog/dialog.ts
  web-test-runner.config.mjs
Labels: patch

#844 fix(expansion-panel): fixed a rendering artifact caused by CSS animation
  src/lib/expansion-panel/_core.scss
Labels: patch

#848 docs: upgrade storybook to v8.6.0
  package-lock.json
  package.json
  src/stories/getting-started/Theming.mdx
Labels: documentation, skip-release

#853 fix(time-picker): remove extra icon margin
  src/lib/time-picker/time-picker-adapter.ts
Labels: patch, skip-release

#850 docs(tooltip): improve anchoring docs
  .prettierignore
  src/stories/components/tooltip/Tooltip.mdx
  src/stories/components/tooltip/Tooltip.stories.ts
Labels: documentation, skip-release

#849 fix(select): fixed a bug where the inset label would not float if the value was set while the dropdown is open
  src/lib/select/select/select-core.ts
  src/lib/select/select/select.test.ts
Labels: patch, skip-release
