Repository tyler-technologies-oss/forge, pull requests merged in 2025-07, with the labels that each got.

#938 feat(badge): update gap spacing
  src/lib/core/styles/tokens/badge/_tokens.scss
  src/stories/components/badge/Badge.mdx
  src/stories/components/badge/Badge.stories.ts
Labels: documentation, patch, skip-release, storybook-preview

#952 fix(overlay): do not hide overlay by default when clipped by ancestors
  src/dev/pages/overlay/overlay.html
  src/lib/overlay/overlay-constants.ts
  src/lib/overlay/overlay.test.ts
  src/lib/overlay/overlay.ts
  src/lib/popover/popover.test.ts
Labels: patch

#956 fix: use modern styles for visually hidden content
  src/lib/utils/_mixins.scss
Labels: patch

#957 fix(list): move margins from host to internal container element
  src/lib/list/list-item/list-item.scss
  src/lib/list/list/list.scss
Labels: patch, storybook-preview

#963 fix(time-picker): allow min and max to wrap around midnight
  src/lib/time-picker/time-picker-core.ts
  src/test/spec/time-picker/time-picker.spec.ts
Labels: patch, storybook-preview

#964 fix(menu): allow cascading menus to use bottom and top placements if left or right isn't available
  src/lib/menu/menu-core.ts
Labels: patch, storybook-preview

#965 fix(field): add overflow and isolation token to the inner container element
  src/lib/core/styles/tokens/field/_tokens.scss
  src/lib/field/_core.scss
  src/lib/field/field.ts
Labels: enhancement, patch

#966 feat(date-range-picker): fixed a bug where the input mask was not being destroyed on end date input if turning off the mask
  src/lib/date-picker/base/base-date-picker-core.ts
  src/lib/date-range-picker/date-range-picker-core.ts
Labels: patch, storybook-preview
