Repository tyler-technologies-oss/forge, pull requests merged in 2025-04, with the labels that each got.

#883 fix: updated how overlay positioning is handled when overflowing the viewport bounds
  src/lib/core/utils/position-utils.ts
  src/lib/overlay/base/base-overlay-core.ts
  src/lib/overlay/base/base-overlay.ts
  src/lib/overlay/base/overlay-aware-core.ts
  src/lib/overlay/overlay-adapter.ts
  src/lib/overlay/overlay-constants.ts
  src/lib/overlay/overlay-core.ts
  src/lib/overlay/overlay.test.ts
  src/lib/overlay/overlay.ts
  src/lib/popover/popover.scss
  src/lib/popover/popover.test.ts
Labels: patch, skip-release, storybook-preview

#895 fix(table): fixed a bug where the table head cell border could be hidden
  src/lib/table/_core.scss
Labels: patch, skip-release

#894 feat(app-bar): remove default auto-theming in favor of scoped CSS variables and theme attribute
  src/dev/pages/app-bar/app-bar.ejs
  src/dev/pages/app-bar/app-bar.html
  src/dev/pages/app-bar/app-bar.scss
  src/dev/pages/app-bar/app-bar.ts
  src/lib/app-bar/app-bar/app-bar-constants.ts
  src/lib/app-bar/app-bar/app-bar-core.ts
  src/lib/app-bar/app-bar/app-bar.scss
  src/lib/app-bar/app-bar/app-bar.test.ts
  src/lib/app-bar/app-bar/app-bar.ts
  src/lib/app-bar/forge-app-bar.scss
  src/lib/app-bar/help-button/app-bar-help-button.html
  src/lib/app-bar/menu-button/app-bar-menu-button.html
  src/lib/app-bar/notification-button/app-bar-notification-button.html
  src/lib/app-bar/profile-button/app-bar-profile-button.html
  src/lib/app-bar/search/app-bar-search.scss
  src/lib/button/button-constants.ts
  src/lib/button/button.scss
  src/lib/core/styles/tokens/app-bar/app-bar/_tokens.scss
  src/lib/icon-button/icon-button-constants.ts
  src/lib/icon-button/icon-button.scss
  src/lib/tabs/tab-bar/tab-bar.scss
  src/stories/components/app-bar/AppBar.mdx
  src/stories/components/app-bar/AppBar.stories.ts
Labels: minor, skip-release, storybook-preview

#896 fix(app-bar): remove default width to allow for wider logos without overriding styles
  src/lib/app-bar/app-bar/_core.scss
Labels: patch, skip-release

#899 feat: expose popover APIs in select, autocomplete, and menu
  plugins/cem/member-deny-list.mjs
  src/lib/autocomplete/autocomplete-core.ts
  src/lib/list-dropdown/list-dropdown-aware-core.ts
  src/lib/list-dropdown/list-dropdown-aware.ts
  src/lib/list-dropdown/list-dropdown-constants.ts
  src/lib/list-dropdown/list-dropdown-utils.ts
  src/lib/menu/menu-core.ts
  src/lib/menu/menu.ts
  src/lib/overlay/base/overlay-aware.ts
  src/lib/select/core/base-select-core.ts
  src/lib/select/select/select.test.ts
  src/lib/select/select/select.ts
  src/stories/components/select/Select.mdx
  src/test/spec/autocomplete/autocomplete.spec.ts
  src/test/spec/menu/menu.spec.ts
Labels: minor, skip-release

#900 fix: readopt styles in Lit-based components when adopted
  plugins/cem/member-deny-list.mjs
  src/lib/avatar/avatar.ts
  src/lib/badge/badge.ts
  src/lib/card/card.ts
  src/lib/core/base/base-lit-element.ts
  src/lib/core/utils/lit-utils.ts
  src/lib/key/key-item/key-item.ts
  src/lib/key/key/key.ts
  src/lib/meter/meter-group/meter-group.ts
  src/lib/meter/meter/meter.ts
Labels: patch

#907 docs(paginator): add missing slot docs
  src/lib/paginator/paginator.ts
Labels: documentation, skip-release

#906 chore(dialog): remove unused slide direction values from `DialogAnimationType`
  src/lib/dialog/dialog-constants.ts
Labels: patch, skip-release

#905 fix(list-item): fixed a bug where multiple clicks on the interactive element could occur
  src/lib/core/utils/event-utils.ts
  src/lib/list/list-item/list-item-core.ts
Labels: patch

#904 fix(expansion-panel): fix connected check
  src/lib/expansion-panel/expansion-panel-core.ts
Labels: patch

#909 fix(toolbar): Apply min-width to grid center slots to allow overflows
  src/lib/toolbar/_core.scss
  src/lib/toolbar/toolbar.scss
Labels: patch, skip-release
