Repository tyler-technologies-oss/forge, pull requests merged in 2025-05, with the labels that each got.

#917 fix(view-switcher): output height and width tokens on host element
  src/lib/view-switcher/view-switcher.scss
  src/lib/view-switcher/view-switcher.ts
Labels: patch, skip-release

#912 chore: consolidating various defineXComponent calls to use the standard forge-core defineCustomElement call
  src/lib/avatar/index.ts
  src/lib/badge/index.ts
  src/lib/card/index.ts
  src/lib/key/key-item/index.ts
  src/lib/key/key/index.ts
  src/lib/meter/meter-group/index.ts
  src/lib/meter/meter/index.ts
Labels: skip-release

#930 Feat/table before render event
  src/lib/table/table-constants.ts
  src/lib/table/table-core.ts
  src/lib/table/table.ts
  src/test/spec/table/table.spec.ts
Labels: minor, skip-release

#933 feat: update dependencies
  .stylelintrc
  forge.json
  package-lock.json
  package.json
  src/lib/calendar/calendar-menu/_variables.scss
  src/lib/color-picker/_mixins.scss
  src/lib/core/styles/theme/_color-utils.scss
  src/lib/core/styles/tokens/app-bar/app-bar/_tokens.scss
  src/lib/drawer/mini-drawer/mini-drawer.scss
Labels: minor, skip-release

#920 Dependency reviewer
  .github/workflows/dependency_enforcement.yml
Labels: skip-release

#934 chore: silence mixed-decls warning in vite
  .storybook/main.ts
  src/dev/vite.config.mts
Labels: skip-release
