Repository tyler-technologies-oss/forge, pull requests merged in 2025-01, with the labels that each got.

#776 fix(text-field): ensure cleanup logic runs when element is disconnected
  src/lib/text-field/text-field.ts
Labels: patch, skip-release

#777 fix(field): adjust input transition to avoid jittery movement when decelerating
  src/lib/core/styles/tokens/field/_tokens.scss
Labels: patch, skip-release

#778 fix(text-field): label will now float when invalid chars are entered in number inputs
  src/lib/text-field/text-field-core.ts
  src/lib/text-field/text-field.test.ts
Labels: patch, skip-release

#779 Docs fixes
  src/lib/date-range-picker/date-range-picker.ts
  src/stories/getting-started/SassLibrary.mdx
Labels: documentation, skip-release

#773 fix(radio): simplify check animation to reduce jitter
  src/lib/core/styles/tokens/radio/_tokens.scss
  src/lib/radio/forge-radio.scss
  src/lib/radio/radio/_core.scss
  src/lib/radio/radio/radio.ts
Labels: patch, skip-release

#780 fix(tooltip): fixed a bug where visually hidden content could cause inadvertent page scrolling
  src/lib/utils/_mixins.scss
Labels: patch

#786 fix(drawer): fixed a bug where the drawer would not repaint after transitioning in Safari
  src/lib/drawer/base/_mixins.scss
  src/lib/drawer/drawer/drawer.scss
Labels: patch

#781 docs(toolbar): fix token names
  src/lib/toolbar/toolbar.ts
Labels: documentation, skip-release

#782 chore(eslint): remove duplicate eslint rules
  .eslintrc.json
Labels: skip-release

#784 fix(drawer): fixed a bug where the drawer would not repaint after transitioning in Safari
  src/dev/pages/drawer/drawer.ejs
  src/dev/pages/drawer/drawer.scss
  src/lib/core/styles/tokens/drawer/mini/_tokens.scss
  src/lib/drawer/base/_core.scss
  src/lib/drawer/drawer/drawer.scss
  src/lib/drawer/mini-drawer/_core.scss
  src/lib/drawer/mini-drawer/mini-drawer.ts
Labels: patch, skip-release

#785 fix: reduce usage of `contain` style to only required instances
  src/lib/avatar/_core.scss
  src/lib/backdrop/_core.scss
  src/lib/divider/_core.scss
  src/lib/linear-progress/_core.scss
  src/lib/split-view/split-view-panel/_mixins.scss
  src/lib/split-view/split-view/_mixins.scss
  src/lib/toolbar/_core.scss
Labels: patch, skip-release

#787 fix(split-view-panel): fixed a bug relating to the open animation direction
  src/lib/split-view/split-view-panel/_mixins.scss
Labels: patch

#797 docs(button-area): add required slotted button to demo
  src/stories/components/button-area/ButtonArea.stories.ts
Labels: documentation, skip-release

#798 fix(app-bar-search): fixed a color contrast issue by increasing the color emphasis on the placeholder text due to the transparent background
  src/lib/core/styles/tokens/app-bar/search/_tokens.scss
Labels: patch, skip-release, accessibility

#793 docs(table): add action logging for `forge-table-select-all` event
  src/stories/components/table/Table.stories.ts
Labels: documentation, skip-release, storybook-preview

#789 docs(design-tokens): add elevation tokens page
  src/stories/design-tokens/Elevation.mdx
  src/stories/design-tokens/Shape.mdx
  src/stories/design-tokens/design-token-utils.tsx
  src/stories/design-tokens/shape-utils.tsx
Labels: documentation, skip-release

#794 fix(autocomplete): fixed a bug where the `wrapOptionText` property was not being set on the list dropdown
  src/lib/autocomplete/autocomplete-core.ts
  src/lib/autocomplete/autocomplete.ts
  src/lib/list-dropdown/list-dropdown-aware.ts
Labels: patch, skip-release

#792 fix(file-picker): cleanup callback to avoid reference being held which can leak
  src/lib/file-picker/file-picker-adapter.ts
  src/lib/file-picker/file-picker-core.ts
Labels: patch, skip-release

#790 fix(label-value): allow for content to wrap long words without overflowing
  src/lib/label-value/_core.scss
Labels: patch, skip-release

#791 Fix/icon button badge dense
  src/lib/core/styles/typography/index.scss
  src/lib/icon-button/icon-button.scss
Labels: patch, skip-release

#795 feat(meter): add meter component
  custom-elements-manifest.config.mjs
  package-lock.json
  package.json
  plugins/cem/member-deny-list.mjs
  src/dev/pages/key/key.ejs
  src/dev/pages/key/key.html
  src/dev/pages/key/key.ts
  src/dev/pages/meter/meter.ejs
  src/dev/pages/meter/meter.html
  src/dev/pages/meter/meter.scss
  src/dev/pages/meter/meter.ts
  src/dev/src/components.json
  src/lib/core/styles/tokens/key/key-item/_tokens.scss
  src/lib/core/styles/tokens/key/key/_tokens.scss
  src/lib/core/styles/tokens/meter/meter-group/_tokens.scss
  src/lib/core/styles/tokens/meter/meter/_tokens.scss
  src/lib/core/utils/a11y-utils.ts
  src/lib/index.ts
  src/lib/key/index.ts
  src/lib/key/key-item/_core.scss
  src/lib/key/key-item/_token-utils.scss
  src/lib/key/key-item/index.scss
  src/lib/key/key-item/index.ts
  src/lib/key/key-item/key-item.scss
  src/lib/key/key-item/key-item.test.ts
  src/lib/key/key-item/key-item.ts
  src/lib/key/key/_core.scss
  src/lib/key/key/_token-utils.scss
  src/lib/key/key/index.scss
  src/lib/key/key/index.ts
  src/lib/key/key/key.scss
  src/lib/key/key/key.test.ts
  src/lib/key/key/key.ts
  src/lib/meter/index.ts
  src/lib/meter/meter-group/_core.scss
  src/lib/meter/meter-group/_token-utils.scss
  src/lib/meter/meter-group/index.scss
  src/lib/meter/meter-group/index.ts
  src/lib/meter/meter-group/meter-group.scss
  src/lib/meter/meter-group/meter-group.test.ts
  src/lib/meter/meter-group/meter-group.ts
  src/lib/meter/meter/_core.scss
  src/lib/meter/meter/_token-utils.scss
  src/lib/meter/meter/index.scss
  src/lib/meter/meter/index.ts
  src/lib/meter/meter/meter.scss
  src/lib/meter/meter/meter.test.ts
  src/lib/meter/meter/meter.ts
  src/stories/blocks/CustomArgTypes.tsx
  src/stories/components/key/Key.mdx
  src/stories/components/key/Key.stories.ts
  src/stories/components/meter/Meter.mdx
  src/stories/components/meter/Meter.stories.ts
  src/stories/getting-started/Usage.mdx
  src/stories/utils.ts
Labels: minor, skip-release, new component, storybook-preview

#788 fix(button-toggle): no longer reflects the `value` attribute to allow for non-string values to be set via JS property
  src/lib/button-toggle/button-toggle.test.ts
  src/lib/button-toggle/button-toggle/button-toggle-core.ts
Labels: patch

#799 fix(list-item): fixed a bug where the selected state overlay could render on top of slotted elements
  package-lock.json
  package.json
  src/lib/list/list-item/_core.scss
Labels: patch, skip-release

#800 fix(defineComponents): fixed an exception caused by lit-based components being incompatible with internal Forge API during element definition
  src/lib/index.ts
Labels: patch
